-- Travel Stories seed data (all 36 states/UTs + marketplace).
-- GENERATED by scripts/seed_convert.py — do not edit by hand.
-- Import ONCE into an empty DB: schema FIRST, then this file.

-- from 20260924082941_seed_travel_data.sql
/*
# Seed Travel Data — States, Districts, Tourist Spots, Accommodations

Populates the database with curated content for five major Indian states:
Kerala, Rajasthan, Goa, Himachal Pradesh, and Tamil Nadu.

Each state includes:
- State metadata (tagline, description, best season, highlights, color)
- Multiple districts with descriptions
- Tourist spots with coordinates, ratings, categories
- Accommodations (hotels, resorts, homestays) across budget/deluxe/luxury tiers

All data is real, curated travel information for demonstration of the
interactive map discovery experience.
*/

-- ============ STATES ============
INSERT INTO states (name, slug, tagline, description, best_season, peak_season, highlights, color) VALUES
('Kerala', 'kerala', 'God''s Own Country', 'A tropical paradise of palm-fringed beaches, serene backwaters, misty hill stations, and vibrant traditions. Kerala offers a unique blend of nature, Ayurveda, and cultural richness.', 'Winter (Oct–Feb)', 'December–January', '["Backwaters & Houseboats", "Munnar Tea Gardens", "Ayurvedic Wellness", "Kathakali Performances", "Spice Plantations"]', '#2f8fff'),
('Rajasthan', 'rajasthan', 'Land of Kings', 'A royal desert state of majestic forts, opulent palaces, and golden sands. Rajasthan is a living museum of Rajput valor, vibrant festivals, and desert adventures.', 'Winter (Oct–Mar)', 'November–February', '["Amber Fort", "Thar Desert Safari", "Lake Pichola", "Pushkar Camel Fair", "Heritage Palaces"]', '#f97316'),
('Goa', 'goa', 'Pearl of the Orient', 'India''s beach capital with golden sands, Portuguese heritage, and a laid-back vibe. Goa blends sun-soaked coastlines with centuries-old churches and a vibrant nightlife.', 'Winter (Nov–Feb)', 'December–January', '["Beaches & Water Sports", "Portuguese Churches", "Goan Cuisine", "Night Markets", "Dudhsagar Falls"]', '#16a34a'),
('Himachal Pradesh', 'himachal-pradesh', 'Land of the Gods', 'A Himalayan wonderland of snow-capped peaks, alpine meadows, and colonial hill stations. Himachal is a haven for trekkers, spiritual seekers, and mountain lovers.', 'Summer (Mar–Jun) & Autumn (Sep–Nov)', 'May–June', '["Shimla Ridge", "Manali Snow Peaks", "Spiti Valley Monasteries", "Kullu Dussehra", "Apple Orchards"]', '#1456e1'),
('Tamil Nadu', 'tamil-nadu', 'Land of Temples', 'A cradle of Dravidian civilization with towering temple gopurams, classical Bharatanatyam, and a coastline along the Bay of Bengal. Tamil Nadu is a cultural and spiritual powerhouse.', 'Winter (Nov–Mar)', 'December–February', '["Meenakshi Temple", "Marina Beach", "Mahabalipuram Shore Temple", "Chola Bronzes", "Carnatic Music"]', '#d97706');

-- ============ DISTRICTS ============
-- Kerala districts
INSERT INTO districts (state_id, name, description) VALUES
((SELECT id FROM states WHERE name='Kerala'), 'Ernakulam', 'Kerala''s commercial capital, home to Kochi with its historic Fort Kochi and bustling harbor.'),
((SELECT id FROM states WHERE name='Kerala'), 'Idukki', 'A high-range district of misty hills, tea plantations, and wildlife sanctuaries, home to Munnar.'),
((SELECT id FROM states WHERE name='Kerala'), 'Alappuzha', 'The Venice of the East, famous for backwaters, houseboats, and snake boat races.'),
((SELECT id FROM states WHERE name='Kerala'), 'Thiruvananthapuram', 'The capital district with ancient temples, museums, and the famous Kovalam beach.'),
((SELECT id FROM states WHERE name='Kerala'), 'Wayanad', 'A lush green plateau of wildlife reserves, prehistoric caves, and spice plantations.');

-- Rajasthan districts
INSERT INTO districts (state_id, name, description) VALUES
((SELECT id FROM states WHERE name='Rajasthan'), 'Jaipur', 'The Pink City, capital of Rajasthan, known for its hilltop forts and grand palaces.'),
((SELECT id FROM states WHERE name='Rajasthan'), 'Udaipur', 'The City of Lakes, a romantic destination of marble palaces and shimmering waters.'),
((SELECT id FROM states WHERE name='Rajasthan'), 'Jaisalmer', 'The Golden City, a living fort in the Thar Desert with golden sandstone architecture.'),
((SELECT id FROM states WHERE name='Rajasthan'), 'Jodhpur', 'The Blue City, dominated by the mighty Mehrangarh Fort.'),
((SELECT id FROM states WHERE name='Rajasthan'), 'Pushkar', 'A sacred pilgrimage town around a holy lake, home to the famous camel fair.');

-- Goa districts
INSERT INTO districts (state_id, name, description) VALUES
((SELECT id FROM states WHERE name='Goa'), 'North Goa', 'The lively northern district with popular beaches, flea markets, and nightlife.'),
((SELECT id FROM states WHERE name='Goa'), 'South Goa', 'The tranquil southern district with pristine beaches and luxury resorts.');

-- Himachal Pradesh districts
INSERT INTO districts (state_id, name, description) VALUES
((SELECT id FROM states WHERE name='Himachal Pradesh'), 'Shimla', 'The former British summer capital with colonial architecture and mountain vistas.'),
((SELECT id FROM states WHERE name='Himachal Pradesh'), 'Kullu', 'The valley of gods, famous for trekking, rafting, and the Dussehra festival.'),
((SELECT id FROM states WHERE name='Himachal Pradesh'), 'Lahaul and Spiti', 'A remote trans-Himalayan valley of ancient monasteries and stark landscapes.'),
((SELECT id FROM states WHERE name='Himachal Pradesh'), 'Solan', 'A gateway district known for its mushroom farming and pleasant climate.');

-- Tamil Nadu districts
INSERT INTO districts (state_id, name, description) VALUES
((SELECT id FROM states WHERE name='Tamil Nadu'), 'Madurai', 'The temple city, home to the magnificent Meenakshi Amman Temple.'),
((SELECT id FROM states WHERE name='Tamil Nadu'), 'Chennai', 'The coastal capital, blending colonial heritage with modern culture and Marina Beach.'),
((SELECT id FROM states WHERE name='Tamil Nadu'), 'Kancheepuram', 'The city of a thousand temples, renowned for silk weaving and ancient shrines.'),
((SELECT id FROM states WHERE name='Tamil Nadu'), 'Kanniyakumari', 'India''s southernmost tip where three seas meet, famous for sunrises and sunsets.');

-- ============ TOURIST SPOTS ============
-- Kerala spots
INSERT INTO tourist_spots (district_id, name, description, category, latitude, longitude, rating, entry_fee, visit_duration) VALUES
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Ernakulam' AND s.name='Kerala'), 'Fort Kochi', 'A historic neighborhood blending Portuguese, Dutch, and British colonial architecture with Chinese fishing nets along the waterfront.', 'Heritage', 9.966100, 76.242300, 4.4, 'Free', '3–4 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Ernakulam' AND s.name='Kerala'), 'Marine Drive Kochi', 'A scenic promenade along the backwaters, perfect for evening strolls and sunset views.', 'Waterfront', 9.979700, 76.283000, 4.2, 'Free', '1–2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Idukki' AND s.name='Kerala'), 'Munnar Tea Gardens', 'Rolling hills blanketed in emerald tea plantations, offering misty vistas and plantation tours.', 'Hill Station', 10.088900, 77.059500, 4.7, 'Free', '4–5 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Idukki' AND s.name='Kerala'), 'Eravikulam National Park', 'A sanctuary for the endangered Nilgiri Tahr, set among shola grasslands and rolling hills.', 'Wildlife', 10.292200, 77.067500, 4.5, '₹125', '2–3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Alappuzha' AND s.name='Kerala'), 'Alappuzha Backwaters', 'A serene network of canals, lagoons, and lakes best explored on traditional houseboats.', 'Backwaters', 9.494500, 76.337700, 4.8, '₹500', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Alappuzha' AND s.name='Kerala'), 'Marari Beach', 'A pristine stretch of golden sand with swaying palms, ideal for relaxation and swimming.', 'Beach', 9.618900, 76.385000, 4.3, 'Free', '2–3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Thiruvananthapuram' AND s.name='Kerala'), 'Kovalam Beach', 'A crescent-shaped beach with a historic lighthouse, known for surfing and Ayurvedic resorts.', 'Beach', 8.382000, 76.972000, 4.4, 'Free', '3–4 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Thiruvananthapuram' AND s.name='Kerala'), 'Padmanabhaswamy Temple', 'An ancient Dravidian-style temple, one of the richest religious institutions in the world.', 'Temple', 8.937400, 76.944700, 4.6, 'Free', '1–2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Wayanad' AND s.name='Kerala'), 'Edakkal Caves', 'Prehistoric rock engravings dating back over 3,000 years, set atop a mountain peak.', 'Heritage', 11.619400, 76.232200, 4.3, '₹20', '2–3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Wayanad' AND s.name='Kerala'), 'Banasura Sagar Dam', 'India''s largest earth dam, surrounded by lush hills and offering boating and trekking.', 'Nature', 11.678300, 75.991100, 4.4, '₹40', '2–3 hours');

-- Rajasthan spots
INSERT INTO tourist_spots (district_id, name, description, category, latitude, longitude, rating, entry_fee, visit_duration) VALUES
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Jaipur' AND s.name='Rajasthan'), 'Amber Fort', 'A majestic hilltop fort of red sandstone and marble, featuring mirror palace halls and elephant rides.', 'Heritage', 26.985500, 75.851300, 4.7, '₹200', '3–4 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Jaipur' AND s.name='Rajasthan'), 'Hawa Mahal', 'The Palace of Winds, a five-story pink sandstone facade with 953 tiny windows.', 'Heritage', 26.923900, 75.826700, 4.5, '₹50', '1 hour'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Jaipur' AND s.name='Rajasthan'), 'City Palace Jaipur', 'A grand royal complex blending Rajput and Mughal architecture, still home to the royal family.', 'Heritage', 26.925800, 75.826100, 4.5, '₹300', '2–3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Udaipur' AND s.name='Rajasthan'), 'Lake Pichola', 'A shimmering artificial lake dotted with island palaces, best explored by boat at sunset.', 'Lake', 24.553100, 73.679000, 4.8, '₹400', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Udaipur' AND s.name='Rajasthan'), 'City Palace Udaipur', 'A sprawling marble palace complex overlooking Lake Pichola, showcasing royal Rajput heritage.', 'Heritage', 24.571200, 73.680000, 4.6, '₹300', '2–3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Jaisalmer' AND s.name='Rajasthan'), 'Jaisalmer Fort', 'A living golden sandstone fort, one of the few inhabited forts in the world, with temples and havelis.', 'Heritage', 26.915700, 70.915700, 4.7, '₹250', '3–4 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Jaisalmer' AND s.name='Rajasthan'), 'Sam Sand Dunes', 'Golden dunes of the Thar Desert, offering camel safaris and cultural performances under the stars.', 'Desert', 26.806700, 70.521000, 4.5, '₹100', 'Half day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Jodhpur' AND s.name='Rajasthan'), 'Mehrangarh Fort', 'A colossal hilltop fort towering over the Blue City, with museum galleries and panoramic views.', 'Heritage', 26.588500, 73.071000, 4.8, '₹200', '3–4 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Jodhpur' AND s.name='Rajasthan'), 'Umaid Bhawan Palace', 'One of the world''s largest royal residences, part palace, part museum, part luxury hotel.', 'Heritage', 26.632000, 73.062000, 4.7, '₹300', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Pushkar' AND s.name='Rajasthan'), 'Pushkar Lake', 'A sacred lake surrounded by 52 bathing ghats and 500 temples, a major pilgrimage site.', 'Spiritual', 26.489900, 74.551100, 4.4, 'Free', '2–3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Pushkar' AND s.name='Rajasthan'), 'Brahma Temple Pushkar', 'One of the very few temples dedicated to Lord Brahma, drawing pilgrims from across India.', 'Temple', 26.487500, 74.551100, 4.5, 'Free', '1 hour');

-- Goa spots
INSERT INTO tourist_spots (district_id, name, description, category, latitude, longitude, rating, entry_fee, visit_duration) VALUES
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='North Goa' AND s.name='Goa'), 'Baga Beach', 'A vibrant beach known for water sports, beach shacks, and energetic nightlife.', 'Beach', 15.548000, 73.751000, 4.3, 'Free', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='North Goa' AND s.name='Goa'), 'Fort Aguada', 'A 17th-century Portuguese fort with a lighthouse overlooking the Arabian Sea.', 'Heritage', 15.747000, 73.749000, 4.4, 'Free', '1–2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='North Goa' AND s.name='Goa'), 'Anjuna Flea Market', 'A famous Wednesday flea market offering handicrafts, jewelry, and Goan souvenirs.', 'Shopping', 15.575000, 73.741000, 4.1, 'Free', '2–3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='South Goa' AND s.name='Goa'), 'Palolem Beach', 'A stunning crescent-shaped beach with calm waters, ideal for swimming and kayaking.', 'Beach', 15.009900, 74.023500, 4.7, 'Free', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='South Goa' AND s.name='Goa'), 'Dudhsagar Falls', 'A spectacular four-tiered waterfall on the Mandovi River, cascading 310 meters.', 'Nature', 15.382000, 74.317000, 4.6, '₹400', 'Half day');

-- Himachal Pradesh spots
INSERT INTO tourist_spots (district_id, name, description, category, latitude, longitude, rating, entry_fee, visit_duration) VALUES
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Shimla' AND s.name='Himachal Pradesh'), 'The Ridge Shimla', 'A wide open space in the heart of Shimla, offering panoramic Himalayan views and colonial landmarks.', 'Hill Station', 31.104500, 77.173400, 4.5, 'Free', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Shimla' AND s.name='Himachal Pradesh'), 'Kalka-Shimla Railway', 'A UNESCO World Heritage narrow-gauge toy train winding through 102 tunnels and mountain vistas.', 'Heritage', 31.103000, 77.170000, 4.6, '₹150', '5–6 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Kullu' AND s.name='Himachal Pradesh'), 'Solang Valley', 'A snow-capped valley offering skiing, paragliding, and breathtaking mountain scenery.', 'Adventure', 32.319000, 77.156000, 4.5, 'Free', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Kullu' AND s.name='Himachal Pradesh'), 'Hadimba Temple', 'An ancient cedar wood temple surrounded by tall deodar forests, a serene spiritual site.', 'Temple', 32.262000, 77.193000, 4.4, 'Free', '1 hour'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Lahaul and Spiti' AND s.name='Himachal Pradesh'), 'Key Monastery', 'A thousand-year-old Tibetan Buddhist monastery perched at 4,166m, overlooking the Spiti Valley.', 'Spiritual', 32.297000, 78.001000, 4.7, 'Free', '2–3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Lahaul and Spiti' AND s.name='Himachal Pradesh'), 'Chandra Taal Lake', 'A crescent-shaped high-altitude lake at 4,300m, surrounded by snow-capped peaks and meadows.', 'Nature', 32.487000, 77.614000, 4.8, 'Free', 'Full day');

-- Tamil Nadu spots
INSERT INTO tourist_spots (district_id, name, description, category, latitude, longitude, rating, entry_fee, visit_duration) VALUES
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Madurai' AND s.name='Tamil Nadu'), 'Meenakshi Amman Temple', 'A towering Dravidian temple complex with 14 gopurams, dedicated to Goddess Meenakshi and Lord Shiva.', 'Temple', 9.919500, 78.119700, 4.8, 'Free', '3–4 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Madurai' AND s.name='Tamil Nadu'), 'Thirumalai Nayakkar Palace', 'A 17th-century palace blending Dravidian and Islamic architecture, with a stunning sound-and-light show.', 'Heritage', 9.919000, 78.121000, 4.3, '₹50', '1–2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Chennai' AND s.name='Tamil Nadu'), 'Marina Beach', 'India''s longest urban beach, stretching 13 km along the Bay of Bengal, perfect for morning walks.', 'Beach', 13.050000, 80.282400, 4.3, 'Free', '2–3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Chennai' AND s.name='Tamil Nadu'), 'Kapaleeshwarar Temple', 'A vibrant 7th-century Shiva temple with a colorful gopuram, a masterpiece of Dravidian architecture.', 'Temple', 13.037800, 80.267600, 4.5, 'Free', '1–2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Kancheepuram' AND s.name='Tamil Nadu'), 'Kailasanathar Temple', 'The oldest structure in Kanchipuram, an 8th-century sandstone temple with intricate carvings.', 'Temple', 12.838000, 79.695000, 4.5, 'Free', '1–2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Kancheepuram' AND s.name='Tamil Nadu'), 'Ekambareswarar Temple', 'One of the five Pancha Bhoota Stalas, representing earth, with a 3,500-year-old mango tree.', 'Temple', 12.847000, 79.699000, 4.6, 'Free', '1–2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Kanniyakumari' AND s.name='Tamil Nadu'), 'Vivekananda Rock Memorial', 'A memorial on a rocky island where Swami Vivekananda meditated, with views of three seas meeting.', 'Spiritual', 8.078000, 77.553000, 4.6, '₹50', '2–3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Kanniyakumari' AND s.name='Tamil Nadu'), 'Kanniyakumari Beach', 'The southernmost tip of India, where the Arabian Sea, Bay of Bengal, and Indian Ocean converge.', 'Beach', 8.083000, 77.533000, 4.4, 'Free', '2 hours');

-- ============ ACCOMMODATIONS ============
-- Kerala accommodations
INSERT INTO accommodations (tourist_spot_id, name, type, tier, price_per_night, rating, amenities, address) VALUES
((SELECT id FROM tourist_spots WHERE name='Fort Kochi'), 'Brunton Boatyard Hotel', 'Hotel', 'Luxury', 8500, 4.6, '["Sea View", "Pool", "Spa", "Restaurant", "Bar", "WiFi"]', 'Calvetty Road, Fort Kochi'),
((SELECT id FROM tourist_spots WHERE name='Fort Kochi'), 'Fort Kochi Homestay', 'Homestay', 'Budget', 1800, 4.3, '["WiFi", "Breakfast", "AC", "Bike Rental"]', 'Princess Street, Fort Kochi'),
((SELECT id FROM tourist_spots WHERE name='Munnar Tea Gardens'), 'The Leaf Munnar Resort', 'Resort', 'Luxury', 12000, 4.7, '["Mountain View", "Pool", "Spa", "Restaurant", "WiFi", "Bonfire"]', 'Chinnakanal, Munnar'),
((SELECT id FROM tourist_spots WHERE name='Munnar Tea Gardens'), 'Munnar Tea County Homestay', 'Homestay', 'Budget', 2200, 4.4, '["Tea Garden View", "Breakfast", "WiFi", "Home Cooked Meals"]', 'Kannan Devan Hills, Munnar'),
((SELECT id FROM tourist_spots WHERE name='Munnar Tea Gardens'), 'Blanket Hotel & Spa', 'Hotel', 'Deluxe', 6500, 4.5, '["Mountain View", "Spa", "Restaurant", "Bar", "WiFi", "Gym"]', 'Surianalle, Munnar'),
((SELECT id FROM tourist_spots WHERE name='Alappuzha Backwaters'), 'Lake Palace Resort', 'Resort', 'Luxury', 15000, 4.8, '["Houseboat", "Pool", "Ayurveda", "Restaurant", "WiFi"]', 'Punnamada, Alappuzha'),
((SELECT id FROM tourist_spots WHERE name='Alappuzha Backwaters'), 'Backwater Homestay Alleppey', 'Homestay', 'Budget', 2500, 4.5, '["Canoe Rides", "Breakfast", "WiFi", "Local Cuisine"]', 'Punnamada, Alappuzha'),
((SELECT id FROM tourist_spots WHERE name='Alappuzha Backwaters'), 'Punnamada Resort', 'Resort', 'Deluxe', 7000, 4.4, '["Pool", "Backwater View", "Restaurant", "WiFi", "Ayurveda"]', 'Punnamada, Alappuzha'),
((SELECT id FROM tourist_spots WHERE name='Kovalam Beach'), 'The Leela Kovalam', 'Resort', 'Luxury', 18000, 4.7, '["Beachfront", "Pool", "Spa", "Restaurant", "Bar", "WiFi", "Gym"]', 'Kovalam Beach'),
((SELECT id FROM tourist_spots WHERE name='Kovalam Beach'), 'Kovalam Beach Homestay', 'Homestay', 'Budget', 1500, 4.2, '["Sea View", "Breakfast", "WiFi", "AC"]', 'Lighthouse Road, Kovalam'),
((SELECT id FROM tourist_spots WHERE name='Padmanabhaswamy Temple'), 'Puthoor Hotel', 'Hotel', 'Deluxe', 4500, 4.3, '["Temple Vicinity", "Restaurant", "WiFi", "AC", "Parking"]', 'East Fort, Thiruvananthapuram');

-- Rajasthan accommodations
INSERT INTO accommodations (tourist_spot_id, name, type, tier, price_per_night, rating, amenities, address) VALUES
((SELECT id FROM tourist_spots WHERE name='Amber Fort'), 'Rambagh Palace', 'Hotel', 'Luxury', 35000, 4.9, '["Heritage Palace", "Pool", "Spa", "Restaurant", "Bar", "WiFi", "Golf"]', 'Bhawani Singh Road, Jaipur'),
((SELECT id FROM tourist_spots WHERE name='Amber Fort'), 'Umaid Mahal Heritage Hotel', 'Hotel', 'Deluxe', 5500, 4.5, '["Heritage", "Restaurant", "WiFi", "AC", "Rooftop Cafe"]', 'C-Scheme, Jaipur'),
((SELECT id FROM tourist_spots WHERE name='Amber Fort'), 'Jaipur Homestay Bagru', 'Homestay', 'Budget', 2000, 4.3, '["Breakfast", "WiFi", "AC", "Block Printing Workshop"]', 'Amer Road, Jaipur'),
((SELECT id FROM tourist_spots WHERE name='Lake Pichola'), 'Taj Lake Palace', 'Hotel', 'Luxury', 42000, 4.9, '["Island Palace", "Pool", "Spa", "Restaurant", "Bar", "WiFi", "Boat Ride"]', 'Lake Pichola, Udaipur'),
((SELECT id FROM tourist_spots WHERE name='Lake Pichola'), 'Udaipur Lakeside Homestay', 'Homestay', 'Budget', 2500, 4.4, '["Lake View", "Breakfast", "WiFi", "Rooftop Terrace"]', 'Hanuman Ghat, Udaipur'),
((SELECT id FROM tourist_spots WHERE name='Lake Pichola'), 'Jagat Niwas Palace', 'Hotel', 'Deluxe', 8000, 4.6, '["Lake View", "Restaurant", "Bar", "WiFi", "AC"]', 'Lal Ghat, Udaipur'),
((SELECT id FROM tourist_spots WHERE name='Jaisalmer Fort'), 'Suryagarh Palace', 'Hotel', 'Luxury', 28000, 4.8, '["Desert Heritage", "Pool", "Spa", "Restaurant", "Bar", "WiFi", "Desert Safari"]', 'Sam Road, Jaisalmer'),
((SELECT id FROM tourist_spots WHERE name='Jaisalmer Fort'), 'Jaisalmer Fort Homestay', 'Homestay', 'Budget', 1800, 4.2, '["Inside Fort", "Breakfast", "WiFi", "Rooftop View"]', 'Fort Road, Jaisalmer'),
((SELECT id FROM tourist_spots WHERE name='Jaisalmer Fort'), 'Gorbandh Palace', 'Hotel', 'Deluxe', 6000, 4.4, '["Pool", "Restaurant", "Bar", "WiFi", "Desert Tours"]', 'Jodhpur Road, Jaisalmer'),
((SELECT id FROM tourist_spots WHERE name='Mehrangarh Fort'), 'Umaid Bhawan Palace Jodhpur', 'Hotel', 'Luxury', 30000, 4.8, '["Royal Palace", "Pool", "Spa", "Restaurant", "Bar", "WiFi", "Museum"]', 'Circuit House Road, Jodhpur'),
((SELECT id FROM tourist_spots WHERE name='Mehrangarh Fort'), 'Jodhpur Heritage Haveli', 'Hotel', 'Deluxe', 5000, 4.5, '["Heritage", "Blue City View", "Restaurant", "WiFi", "AC"]', 'Navchokiya, Jodhpur'),
((SELECT id FROM tourist_spots WHERE name='Pushkar Lake'), 'Pushkar Palace Heritage', 'Hotel', 'Deluxe', 4500, 4.4, '["Lake View", "Heritage", "Restaurant", "WiFi", "Garden"]', 'Pushkar Lake Road'),
((SELECT id FROM tourist_spots WHERE name='Pushkar Lake'), 'Pushkar Homestay', 'Homestay', 'Budget', 1500, 4.1, '["Breakfast", "WiFi", "Rooftop", "Temple Walk"]', 'Brahma Temple Road, Pushkar');

-- Goa accommodations
INSERT INTO accommodations (tourist_spot_id, name, type, tier, price_per_night, rating, amenities, address) VALUES
((SELECT id FROM tourist_spots WHERE name='Baga Beach'), 'W Goa', 'Resort', 'Luxury', 22000, 4.7, '["Beachfront", "Pool", "Spa", "Restaurant", "Bar", "WiFi", "Gym", "Nightclub"]', 'Vagator, North Goa'),
((SELECT id FROM tourist_spots WHERE name='Baga Beach'), 'Baga Beach Shack Stay', 'Homestay', 'Budget', 1500, 4.0, '["Beach View", "Breakfast", "WiFi", "Beach Access"]', 'Baga Beach Road'),
((SELECT id FROM tourist_spots WHERE name='Baga Beach'), 'Acron Waterfront Resort', 'Hotel', 'Deluxe', 7500, 4.4, '["Riverside", "Pool", "Restaurant", "Bar", "WiFi", "Water Sports"]', 'Baga River, North Goa'),
((SELECT id FROM tourist_spots WHERE name='Palolem Beach'), 'The Lalit Golf & Spa Resort', 'Resort', 'Luxury', 25000, 4.8, '["Beachfront", "Golf", "Spa", "Pool", "Restaurant", "Bar", "WiFi"]', 'Raj Bagan, Canacona'),
((SELECT id FROM tourist_spots WHERE name='Palolem Beach'), 'Palolem Beach Huts', 'Homestay', 'Budget', 1200, 4.2, '["Beachfront", "Breakfast", "WiFi", "Kayaking"]', 'Palolem Beach'),
((SELECT id FROM tourist_spots WHERE name='Palolem Beach'), 'Coco Goa Eco Resort', 'Resort', 'Deluxe', 6500, 4.5, '["Eco Huts", "Pool", "Restaurant", "WiFi", "Yoga", "Spa"]', 'Palolem, Canacona'),
((SELECT id FROM tourist_spots WHERE name='Dudhsagar Falls'), 'Dudhsagar Spa Resort', 'Resort', 'Deluxe', 5500, 4.3, '["Jungle View", "Pool", "Spa", "Restaurant", "WiFi", "Trekking"]', 'Mollem, South Goa');

-- Himachal Pradesh accommodations
INSERT INTO accommodations (tourist_spot_id, name, type, tier, price_per_night, rating, amenities, address) VALUES
((SELECT id FROM tourist_spots WHERE name='The Ridge Shimla'), 'The Oberoi Wildflower Hall', 'Hotel', 'Luxury', 28000, 4.8, '["Mountain View", "Spa", "Pool", "Restaurant", "Bar", "WiFi", "Gym"]', 'Chharabra, Shimla'),
((SELECT id FROM tourist_spots WHERE name='The Ridge Shimla'), 'Shimla British Home', 'Homestay', 'Budget', 2500, 4.4, '["Heritage", "Breakfast", "WiFi", "Fireplace", "Mountain View"]', 'Mall Road, Shimla'),
((SELECT id FROM tourist_spots WHERE name='The Ridge Shimla'), 'Clarkes Hotel', 'Hotel', 'Deluxe', 7000, 4.5, '["Heritage", "Restaurant", "Bar", "WiFi", "AC", "Garden"]', 'The Mall, Shimla'),
((SELECT id FROM tourist_spots WHERE name='Solang Valley'), 'Manu Allaya Resort', 'Resort', 'Deluxe', 8000, 4.5, '["Mountain View", "Pool", "Spa", "Restaurant", "WiFi", "Bonfire"]', 'Log Huts, Manali'),
((SELECT id FROM tourist_spots WHERE name='Solang Valley'), 'Solang Valley Homestay', 'Homestay', 'Budget', 1800, 4.2, '["Valley View", "Breakfast", "WiFi", "Ski Rental", "Home Meals"]', 'Solang Village, Manali'),
((SELECT id FROM tourist_spots WHERE name='Solang Valley'), 'The Himalayan', 'Hotel', 'Luxury', 15000, 4.7, '["Castle Heritage", "Pool", "Spa", "Restaurant", "Bar", "WiFi", "Garden"]', 'Naggar Road, Manali'),
((SELECT id FROM tourist_spots WHERE name='Key Monastery'), 'Spiti Valley Homestay', 'Homestay', 'Budget', 1200, 4.5, '["Monastery View", "Breakfast", "WiFi", "Local Meals", "Cultural Tours"]', 'Kaza, Spiti'),
((SELECT id FROM tourist_spots WHERE name='Chandra Taal Lake'), 'Chandra Taal Camp', 'Homestay', 'Budget', 2000, 4.3, '["Lake View", "Tented Stay", "Meals", "Bonfire", "Stargazing"]', 'Chandra Taal, Spiti');

-- Tamil Nadu accommodations
INSERT INTO accommodations (tourist_spot_id, name, type, tier, price_per_night, rating, amenities, address) VALUES
((SELECT id FROM tourist_spots WHERE name='Meenakshi Amman Temple'), 'Heritage Madurai', 'Hotel', 'Luxury', 12000, 4.7, '["Heritage", "Pool", "Spa", "Restaurant", "Bar", "WiFi", "Garden"]', 'Melakkal, Madurai'),
((SELECT id FROM tourist_spots WHERE name='Meenakshi Amman Temple'), 'Madurai Temple View Homestay', 'Homestay', 'Budget', 1800, 4.3, '["Temple View", "Breakfast", "WiFi", "AC", "Local Guide"]', 'West Chitrai Street, Madurai'),
((SELECT id FROM tourist_spots WHERE name='Meenakshi Amman Temple'), 'Taj Madurai', 'Hotel', 'Deluxe', 6500, 4.5, '["Pool", "Restaurant", "Bar", "WiFi", "Gym", "Spa"]', '94 Alagarkoil Road, Madurai'),
((SELECT id FROM tourist_spots WHERE name='Marina Beach'), 'Taj Coromandel Chennai', 'Hotel', 'Luxury', 18000, 4.8, '["Pool", "Spa", "Restaurant", "Bar", "WiFi", "Gym", "Business Center"]', 'MRC Nagar, Chennai'),
((SELECT id FROM tourist_spots WHERE name='Marina Beach'), 'Marina Beach Homestay', 'Homestay', 'Budget', 1500, 4.1, '["Beach Walk", "Breakfast", "WiFi", "AC"]', 'Santhome, Chennai'),
((SELECT id FROM tourist_spots WHERE name='Marina Beach'), 'The Park Chennai', 'Hotel', 'Deluxe', 7000, 4.4, '["Pool", "Restaurant", "Bar", "WiFi", "Gym", "Spa"]', 'Anna Salai, Chennai'),
((SELECT id FROM tourist_spots WHERE name='Vivekananda Rock Memorial'), 'Sparsa Resort Kanniyakumari', 'Resort', 'Deluxe', 5500, 4.4, '["Sea View", "Pool", "Restaurant", "WiFi", "AC", "Garden"]', 'Kanniyakumari Beach Road'),
((SELECT id FROM tourist_spots WHERE name='Vivekananda Rock Memorial'), 'Kanniyakumari Homestay', 'Homestay', 'Budget', 1200, 4.0, '["Sunrise View", "Breakfast", "WiFi", "AC"]', 'Beach Road, Kanniyakumari');


-- from 20260925035138_seed_agent_marketplace_data.sql
/*
# Seed Travel Agent Marketplace Data

Populates travel_agents and travel_packages with curated content for
demonstration of the agent marketplace feature.

## Agents
- 4 verified travel agents with ratings and contact info

## Packages
- 10 curated tour packages across Heritage, Beach, Adventure, Honeymoon,
  and Pilgrimage categories, covering Kerala, Rajasthan, Goa, Himachal,
  and Tamil Nadu.
*/

-- ============ AGENTS ============
INSERT INTO travel_agents (name, logo_url, verified, rating, description, contact_email, contact_phone) VALUES
('Wanderlust India Tours', NULL, true, 4.7, 'Award-winning travel agency specializing in curated cultural and heritage tours across India. 15+ years of experience crafting unforgettable journeys.', 'hello@wanderlustindia.com', '+91 98765 43210'),
('Royal Routes Travel', NULL, true, 4.8, 'Premium tour operator focused on luxury desert and palace experiences in Rajasthan. Featured in Conde Nast Traveller.', 'book@royalroutes.in', '+91 99887 76655'),
('Himalayan Adventures Co.', NULL, true, 4.6, 'Adventure travel specialists for trekking, skiing, and mountain expeditions in the Indian Himalayas. Certified mountain guides.', 'info@himalayanadventures.co', '+91 90123 45678'),
('Coastal Dreams Holidays', NULL, true, 4.5, 'Beach and backwater vacation experts covering Goa, Kerala, and Karnataka. All-inclusive packages with stays and activities.', 'contact@coastaldreams.in', '+91 91234 56789');

-- ============ PACKAGES ============
INSERT INTO travel_packages (agent_id, title, slug, description, state_name, duration_days, price, inclusions, exclusions, itinerary, image_url, rating, category, max_group_size) VALUES
((SELECT id FROM travel_agents WHERE name='Wanderlust India Tours'),
'Kerala Backwaters & Hills Escape',
'kerala-backwaters-hills-escape',
'Experience the best of God''s Own Country — from serene backwater houseboats to misty tea gardens. This 6-day tour covers Fort Kochi, Munnar''s tea plantations, Alleppey houseboats, and Kovalam beach.',
'Kerala', 6, 32000,
'["5 nights accommodation (3-star + houseboat)", "Daily breakfast & dinner", "Private AC vehicle for transfers", "Houseboat cruise with all meals", "Sightseeing as per itinerary", "English-speaking guide", "All tolls, parking, fuel"]',
'["Airfare", "Lunch", "Personal expenses", "Travel insurance", "Ayurveda treatments", "Entry tickets to monuments"]',
'["Day 1: Arrive Kochi — Fort Kochi & Marine Drive sightseeing", "Day 2: Kochi to Munnar — tea gardens & Eravikulam National Park", "Day 3: Munnar local — Mattupetty Dam, Echo Point, Spice Plantation", "Day 4: Munnar to Alleppey — board houseboat, backwater cruise", "Day 5: Alleppey to Kovalam — beach visit & lighthouse", "Day 6: Kovalam to Trivandrum — Padmanabhaswamy Temple, departure"]',
'https://images.pexels.com/photos/36998153/pexels-photo-36998153.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
4.7, 'Heritage', 12),

((SELECT id FROM travel_agents WHERE name='Royal Routes Travel'),
'Royal Rajasthan Heritage Tour',
'royal-rajasthan-heritage-tour',
'A majestic 8-day journey through the Land of Kings. Explore the Pink City of Jaipur, the Blue City of Jodhpur, the Golden Fort of Jaisalmer, and the romantic lakes of Udaipur. Stay in heritage hotels and palaces.',
'Rajasthan', 8, 55000,
'["7 nights heritage hotel accommodation", "Daily breakfast & dinner", "Private AC SUV (Innova)", "Camel safari in Jaisalmer", "Boat ride at Lake Pichola", "English-speaking guide", "All monument entry tickets", "Cultural evening in Jaipur"]',
'["Airfare or train tickets", "Lunch", "Personal expenses", "Travel insurance", "Alcoholic beverages", "Tips"]',
'["Day 1: Arrive Jaipur — Amber Fort, Hawa Mahal, City Palace", "Day 2: Jaipur to Jodhpur — Mehrangarh Fort, Umaid Bhawan", "Day 3: Jodhpur to Jaisalmer — evening at Sam Sand Dunes", "Day 4: Jaisalmer — Jaisalmer Fort, Patwon ki Haveli, camel safari", "Day 5: Jaisalmer to Udaipur — en route Ranakpur Jain Temple", "Day 6: Udaipur — City Palace, Lake Pichola boat ride", "Day 7: Udaipur — Jagdish Temple, Saheliyon ki Bari, local markets", "Day 8: Udaipur departure"]',
'https://images.pexels.com/photos/30573733/pexels-photo-30573733.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
4.8, 'Heritage', 10),

((SELECT id FROM travel_agents WHERE name='Royal Routes Travel'),
'Pushkar & Ajmer Spiritual Retreat',
'pushkar-ajmar-spiritual-retreat',
'A soul-stirring 3-day pilgrimage to the sacred town of Pushkar. Visit the Brahma Temple, holy Pushkar Lake, and experience the spiritual essence of Rajasthan.',
'Rajasthan', 3, 12000,
'["2 nights heritage hotel", "Daily breakfast", "Private AC vehicle", "Pushkar Lake aarti experience", "Guide for temple visits", "All tolls and parking"]',
'["Airfare or train tickets", "Lunch and dinner", "Personal expenses", "Travel insurance", "Shopping"]',
'["Day 1: Arrive Pushkar — evening aarti at Pushkar Lake", "Day 2: Brahma Temple, Savitri Mata Temple (cable car), local markets", "Day 3: Ajmer Sharif Dargah visit, departure"]',
'https://images.pexels.com/photos/32261806/pexels-photo-32261806.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
4.5, 'Pilgrimage', 15),

((SELECT id FROM travel_agents WHERE name='Himalayan Adventures Co.'),
'Spiti Valley Expedition',
'spiti-valley-expedition',
'An adrenaline-pumping 7-day expedition to the remote trans-Himalayan valley of Spiti. Visit ancient monasteries, high-altitude lakes, and experience raw mountain beauty. Includes acclimatization days.',
'Himachal Pradesh', 7, 38000,
'["6 nights homestay & camp accommodation", "All meals (vegetarian)", "Private 4x4 vehicle", "Key Monastery visit", "Chandra Taal Lake excursion", "Certified mountain guide", "First aid & oxygen support", "Permits and fees"]',
'["Airfare or bus to Manali", "Personal trekking gear", "Travel insurance", "Alcoholic beverages", "Emergency evacuation", "Photography fees"]',
'["Day 1: Manali to Kaza via Rohtang Pass & Kunzum La", "Day 2: Kaza — Key Monastery & Kibber village", "Day 3: Kaza to Chandratal Lake — camp overnight", "Day 4: Chandratal to Kaza — rest & acclimatization", "Day 5: Kaza to Tabo — Tabo Monastery (1,000 years old)", "Day 6: Tabo to Nako — Nako Lake & village", "Day 7: Nako to Manali via Kinnaur valley"]',
'https://images.pexels.com/photos/37911658/pexels-photo-37911658.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
4.6, 'Adventure', 8),

((SELECT id FROM travel_agents WHERE name='Himalayan Adventures Co.'),
'Shimla & Manali Honeymoon Package',
'shimla-manali-honeymoon',
'A romantic 6-day getaway to the Himalayan hill stations of Shimla and Manali. Enjoy snow-capped peaks, colonial charm, cozy evenings by the bonfire, and breathtaking mountain vistas.',
'Himachal Pradesh', 6, 28000,
'["5 nights 3-star hotel (deluxe room)", "Daily breakfast & dinner", "Private AC vehicle", "Solang Valley excursion", "Hadimba Temple visit", "Kalka-Shimla toy train ride", "Bonfire evening in Manali", "Welcome drink on arrival"]',
'["Airfare", "Lunch", "Personal expenses", "Travel insurance", "Skiing or paragliding charges", "Snow clothing rental"]',
'["Day 1: Arrive Shimla — Mall Road & Ridge", "Day 2: Kalka-Shimla toy train, Jakhoo Temple", "Day 3: Shimla to Manali — en route Kullu valley", "Day 4: Manali — Hadimba Temple, Old Manali, Vashisht hot springs", "Day 5: Solang Valley — snow activities & adventure sports", "Day 6: Manali departure"]',
'https://images.pexels.com/photos/29494184/pexels-photo-29494184.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
4.5, 'Honeymoon', 6),

((SELECT id FROM travel_agents WHERE name='Coastal Dreams Holidays'),
'Goa Beach Bliss Package',
'goa-beach-bliss-package',
'Unwind on the golden sands of Goa with this 4-day beach vacation. Cover North Goa''s vibrant beaches, historic Portuguese landmarks, and South Goa''s serene shores. Perfect for couples and families.',
'Goa', 4, 18000,
'["3 nights beachfront resort", "Daily breakfast", "Private AC vehicle for transfers", "Dudhsagar Falls trip", "Fort Aguada visit", "River cruise with dinner", "All tolls and parking"]',
'["Airfare", "Lunch & dinner (except river cruise)", "Water sports activities", "Personal expenses", "Travel insurance", "Nightclub entry"]',
'["Day 1: Arrive Goa — check-in, Baga Beach evening", "Day 2: North Goa — Fort Aguada, Anjuna flea market, Calangute", "Day 3: South Goa — Palolem Beach, Dudhsagar Falls", "Day 4: Old Goa churches, Mandovi river cruise, departure"]',
'https://images.pexels.com/photos/28159570/pexels-photo-28159570.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
4.4, 'Beach', 15),

((SELECT id FROM travel_agents WHERE name='Wanderlust India Tours'),
'Tamil Nadu Temple Trail',
'tamil-nadu-temple-trail',
'A spiritual and cultural 5-day journey through Tamil Nadu''s greatest temples. From the Meenakshi Temple in Madurai to the shore temples of Mahabalipuram, discover 1,500 years of Dravidian architecture.',
'Tamil Nadu', 5, 25000,
'["4 nights 3-star hotel", "Daily breakfast & dinner", "Private AC vehicle", "All temple entry fees", "English-speaking guide", "Marina Beach walk", "Classical dance performance"]',
'["Airfare or train tickets", "Lunch", "Personal expenses", "Travel insurance", "Shopping", "Photography fees at temples"]',
'["Day 1: Arrive Chennai — Marina Beach, Kapaleeshwarar Temple", "Day 2: Chennai to Mahabalipuram — Shore Temple, Arjuna''s Penance", "Day 3: Mahabalipuram to Kanchipuram — Ekambareswarar & Kailasanathar Temples", "Day 4: Kanchipuram to Madurai — Meenakshi Temple, Thirumalai Nayakkar Palace", "Day 5: Madurai to Kanniyakumari — Vivekananda Rock, sunset at three seas"]',
'https://images.pexels.com/photos/6667281/pexels-photo-6667281.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
4.7, 'Pilgrimage', 12),

((SELECT id FROM travel_agents WHERE name='Coastal Dreams Holidays'),
'Kerala Houseboat Romance',
'kerala-houseboat-romance',
'A intimate 4-day escape for couples through Kerala''s backwaters. Private houseboat stay, candlelight dinner on the deck, Ayurvedic spa, and sunset at Kovalam beach.',
'Kerala', 4, 22000,
'["1 night private houseboat with all meals", "2 nights beachfront resort", "Daily breakfast (except houseboat)", "Private AC vehicle", "Candlelight dinner on houseboat", "Ayurvedic massage session", "Sunset at Kovalam Beach"]',
'["Airfare", "Lunch on non-houseboat days", "Personal expenses", "Travel insurance", "Extra Ayurveda treatments", "Alcoholic beverages"]',
'["Day 1: Arrive Kochi — transfer to Alleppey, board houseboat", "Day 2: Houseboat cruise — disembark, drive to Kovalam", "Day 3: Kovalam — beach, lighthouse, Ayurvedic spa", "Day 4: Trivandrum sightseeing, departure"]',
'https://images.pexels.com/photos/32518360/pexels-photo-32518360.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
4.6, 'Honeymoon', 4),

((SELECT id FROM travel_agents WHERE name='Royal Routes Travel'),
'Jaisalmer Desert Adventure',
'jaisalmer-desert-adventure',
'A thrilling 4-day desert adventure in the Golden City. Camel safaris, overnight desert camps under the stars, and exploration of the living Jaisalmer Fort.',
'Rajasthan', 4, 16000,
'["1 night heritage hotel, 1 night desert camp", "Daily breakfast & dinner", "Private AC vehicle", "Camel safari to Sam Dunes", "Overnight desert camp with cultural program", "Jaisalmer Fort guided tour", "All entry tickets"]',
'["Airfare or train tickets", "Lunch", "Personal expenses", "Travel insurance", "Desert quad biking", "Alcoholic beverages"]',
'["Day 1: Arrive Jaisalmer — Fort, Patwon ki Haveli, Gadisar Lake", "Day 2: Jaisalmer to Sam — camel safari, desert camp, folk music", "Day 3: Desert sunrise, return to Jaisalmer — local markets, Jain temples", "Day 4: Bada Bagh, Vyas Chhatri, departure"]',
'https://images.pexels.com/photos/9497619/pexels-photo-9497619.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
4.5, 'Adventure', 10),

((SELECT id FROM travel_agents WHERE name='Wanderlust India Tours'),
'Goa & Karnataka Coastal Discovery',
'goa-karnataka-coastal-discovery',
'A 7-day coastal journey from Goa''s beaches to Karnataka''s heritage sites. Explore Portuguese churches, Dudhsagar Falls, Hampi ruins, and Gokarna''s pristine beaches.',
'Goa', 7, 35000,
'["6 nights accommodation (3-star)", "Daily breakfast", "Private AC vehicle", "Dudhsagar Falls trip", "Hampi guided tour", "All monument entries", "River cruise in Goa"]',
'["Airfare", "Lunch & dinner", "Personal expenses", "Travel insurance", "Water sports", "Alcoholic beverages"]',
'["Day 1: Arrive Goa — Baga & Calangute beaches", "Day 2: Old Goa churches, Fort Aguada, Anjuna market", "Day 3: Dudhsagar Falls, drive to Gokarna", "Day 4: Gokarna beaches — Om Beach, Kudle Beach", "Day 5: Gokarna to Hampi — Virupaksha Temple", "Day 6: Hampi ruins — Vittala Temple, Lotus Mahal, Elephant Stables", "Day 7: Hampi to Goa, departure"]',
'https://images.pexels.com/photos/8037061/pexels-photo-8037061.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
4.3, 'Beach', 12);


-- from 20260926000002_seed_remaining_states.sql
/*
# Seed Remaining States Data — Pan-India coverage (31 states/UTs)

Extends the database from the initial 5 states to all 36 states/UTs of India.
District names match the TopoJSON `district` properties exactly so every
district highlights and is clickable on its state map.

States added: Andhra Pradesh, Arunachal Pradesh, Assam, Bihar, Chhattisgarh,
Gujarat, Haryana, Jharkhand, Karnataka, Madhya Pradesh, Maharashtra, Manipur,
Meghalaya, Mizoram, Nagaland, Odisha, Punjab, Sikkim, Telangana, Tripura,
Uttar Pradesh, Uttarakhand, West Bengal, Andaman and Nicobar Islands,
Chandigarh, Dadra and Nagar Haveli and Daman and Diu, Delhi,
Jammu and Kashmir, Ladakh, Lakshadweep, Puducherry.

Idempotent: all INSERTs use ON CONFLICT DO NOTHING.
*/

-- ============ STATES ============
INSERT INTO states (name, slug, tagline, description, best_season, peak_season, highlights, color) VALUES
('Andhra Pradesh', 'andhra-pradesh', 'Land of Temples and Coastlines', 'A southeastern state of ancient Buddhist sites, Tirupati pilgrimage, and a long Bay of Bengal coastline with growing port cities.', 'Winter (Nov-Feb)', 'January', '["Tirupati Balaji Temple", "Araku Valley", "Amaravati Stupa", "Vizag Beaches", "Lepakshi Temple"]', '#0ea5e9'),
('Arunachal Pradesh', 'arunachal-pradesh', 'Land of the Dawn-Lit Mountains', 'India''s easternmost frontier of Himalayan monasteries, alpine passes, and tribal cultures, crowned by Tawang Monastery.', 'Spring (Mar-May)', 'April', '["Tawang Monastery", "Sela Pass", "Ziro Valley", "Namdapha Forests", "Dirang Valley"]', '#0d9488'),
('Assam', 'assam', 'Gateway to the Northeast', 'A Brahmaputra valley state of one-horned rhinos at Kaziranga, tea gardens, the Kamakhya Shakti shrine, and Ahom heritage.', 'Winter (Nov-Mar)', 'February', '["Kaziranga Rhinos", "Kamakhya Temple", "Majuli Island", "Tea Gardens", "Manas National Park"]', '#65a30d'),
('Bihar', 'bihar', 'Cradle of Empires and Enlightenment', 'An ancient land of Nalanda''s university ruins, the Mahabodhi Temple where Buddha attained enlightenment, and Mauryan history.', 'Winter (Oct-Mar)', 'November', '["Mahabodhi Temple", "Nalanda Ruins", "Golghar Patna", "Vikramshila", "Rajgir Hot Springs"]', '#b45309'),
('Chhattisgarh', 'chhattisgarh', 'Land of Waterfalls and Tribes', 'A central Indian state of dense forests, Bastar tribal culture, and Chitrakote — the Niagara of India.', 'Winter (Oct-Mar)', 'December', '["Chitrakote Falls", "Bastar Tribal Culture", "Bhoramdeo Temple", "Kanger Valley", "Sirpur Heritage"]', '#15803d'),
('Gujarat', 'gujarat', 'Land of Legends and Lions', 'A western state of Asiatic lions at Gir, the white Rann of Kutch, Somnath Jyotirlinga, and Mahatma Gandhi''s Sabarmati Ashram.', 'Winter (Nov-Feb)', 'December', '["Rann of Kutch", "Gir Lions", "Somnath Temple", "Sabarmati Ashram", "Statue of Unity"]', '#db2777'),
('Haryana', 'haryana', 'Land of Kurukshetra', 'A northern plains state around Delhi of Mahabharata heritage at Kurukshetra, Surajkund crafts, and modern Gurugram.', 'Winter (Oct-Mar)', 'November', '["Brahma Sarovar", "Surajkund Mela", "Sultanpur Bird Sanctuary", "Kingdom of Dreams", "Pinjore Gardens"]', '#7c3aed'),
('Jharkhand', 'jharkhand', 'Land of Forests and Falls', 'A mineral-rich eastern state of waterfalls around Ranchi, the Baidyanath Jyotirlinga at Deoghar, and tribal culture.', 'Winter (Oct-Mar)', 'December', '["Hundru Falls", "Baidyanath Temple", "Betla National Park", "Dassam Falls", "Parasnath Hill"]', '#047857'),
('Karnataka', 'karnataka', 'Land of Heritage and Hills', 'A southern state of Hampi''s Vijayanagara ruins, Mysuru Palace, Coorg coffee hills, and Bengaluru''s tech buzz.', 'Winter (Oct-Feb)', 'December', '["Hampi Ruins", "Mysuru Palace", "Coorg Hills", "Jog Falls", "Gokarna Beaches"]', '#9333ea'),
('Madhya Pradesh', 'madhya-pradesh', 'Heart of Incredible India', 'India''s central state of Khajuraho temples, Sanchi Stupa, tiger reserves, and the holy city of Ujjain.', 'Winter (Oct-Mar)', 'November', '["Khajuraho Temples", "Sanchi Stupa", "Bandhavgarh Tigers", "Mahakaleshwar Ujjain", "Bhimbetka Caves"]', '#c2410c'),
('Maharashtra', 'maharashtra', 'Gateway to the Heart of India', 'A western powerhouse of Mumbai''s Gateway, Ellora and Ajanta cave temples, hill forts, and Konkan beaches.', 'Winter (Nov-Feb)', 'December', '["Gateway of India", "Ellora Caves", "Shaniwar Wada", "Lonavala Hills", "Tadoba Tigers"]', '#e11d48'),
('Manipur', 'manipur', 'Jewel of India', 'A northeastern valley state of Loktak floating lake, Kangla heritage, polo origins, and vibrant markets run by women.', 'Spring (Feb-May)', 'March', '["Loktak Lake", "Kangla Palace", "Ima Keithel Market", "Keibul Lamjao", "Shirui Hills"]', '#059669'),
('Meghalaya', 'meghalaya', 'Abode of the Clouds', 'A hill state of living root bridges, Asia''s cleanest village Mawlynnong, dramatic waterfalls, and cave systems.', 'Autumn (Sep-Nov)', 'October', '["Living Root Bridges", "Nohkalikai Falls", "Mawlynnong Village", "Dawki River", "Mawsmai Caves"]', '#0891b2'),
('Mizoram', 'mizoram', 'Land of the Highlanders', 'A northeastern hill state of ridgeline towns, bamboo forests, and serene Aizawl valley culture.', 'Winter (Nov-Feb)', 'December', '["Durtlang Hills", "Reiek Peak", "Vantawng Falls", "Murlen Park", "Solomon''s Temple"]', '#4d7c0f'),
('Nagaland', 'nagaland', 'Land of Festivals', 'A hill state of Naga tribes, the Hornbill Festival at Kisama, and the historic Kohima War Cemetery.', 'Winter (Oct-Dec)', 'December', '["Hornbill Festival", "Kohima War Cemetery", "Dzukou Valley", "Kisama Village", "Japfu Peak"]', '#6d28d9'),
('Odisha', 'odisha', 'Soul of Incredible India', 'An eastern coastal state of the Jagannath Temple, Konark Sun Temple, Chilika lagoon, and classical Odissi dance.', 'Winter (Oct-Feb)', 'December', '["Jagannath Temple", "Konark Sun Temple", "Chilika Lake", "Puri Beach", "Lingaraj Temple"]', '#0e7490'),
('Punjab', 'punjab', 'Land of Five Rivers', 'A northwestern state of the Golden Temple at Amritsar, Sikh heritage, mustard fields, and legendary hospitality.', 'Winter (Oct-Mar)', 'November', '["Golden Temple", "Wagah Border Ceremony", "Jallianwala Bagh", "Qila Mubarak", "Anandpur Sahib"]', '#ca8a04'),
('Sikkim', 'sikkim', 'Himalayan Paradise', 'A Himalayan state of monasteries, Kanchenjunga views, Yumthang flowers, and India''s first organic state.', 'Spring (Mar-May)', 'April', '["Rumtek Monastery", "Yumthang Valley", "Gurudongmar Lake", "MG Marg Gangtok", "Nathula Pass"]', '#2563eb'),
('Telangana', 'telangana', 'Land of Charminar', 'India''s youngest state of Hyderabad''s Charminar and Golconda, Warangal Kakatiya temples, and Deccan cuisine.', 'Winter (Nov-Feb)', 'December', '["Charminar", "Golconda Fort", "Thousand Pillar Temple", "Ramoji Film City", "Nagarjuna Sagar"]', '#be123c'),
('Tripura', 'tripura', 'Land of Palaces and Temples', 'A northeastern state of Ujjayanta Palace, Tripura Sundari Shakti shrine, and bamboo craft traditions.', 'Winter (Oct-Mar)', 'November', '["Ujjayanta Palace", "Tripura Sundari Temple", "Neermahal Palace", "Unakoti Rock Carvings", "Sepahijala Wildlife"]', '#a16207'),
('Uttar Pradesh', 'uttar-pradesh', 'Heartland of Heritage', 'India''s most populous state of the Taj Mahal, Varanasi ghats, Lucknow tehzeeb, and Mathura-Vrindavan devotion.', 'Winter (Oct-Mar)', 'November', '["Taj Mahal", "Varanasi Ghats", "Bara Imambara", "Sarnath", "Fatehpur Sikri"]', '#9a3412'),
('Uttarakhand', 'uttarakhand', 'Land of the Gods', 'A Himalayan state of Char Dham pilgrimage, Rishikesh yoga, Nainital lakes, and Valley of Flowers treks.', 'Summer (Mar-Jun)', 'May', '["Kedarnath Temple", "Naini Lake", "Rishikesh Yoga", "Valley of Flowers", "Har Ki Dun Trek"]', '#1d4ed8'),
('West Bengal', 'west-bengal', 'City of Joy and Beyond', 'An eastern state of Kolkata''s colonial grandeur, Darjeeling tea and toy train, and Sundarbans mangroves.', 'Winter (Oct-Mar)', 'December', '["Victoria Memorial", "Darjeeling Toy Train", "Howrah Bridge", "Sundarbans", "Dakshineswar Temple"]', '#b91c1c'),
('Andaman and Nicobar Islands', 'andaman-and-nicobar-islands', 'Emerald Islands', 'A Bay of Bengal archipelago of Cellular Jail history, Radhanagar Beach, and world-class diving reefs.', 'Winter (Nov-Apr)', 'December', '["Cellular Jail", "Radhanagar Beach", "Scuba Diving", "Ross Island", "Limestone Caves"]', '#155e75'),
('Chandigarh', 'chandigarh', 'The City Beautiful', 'India''s first planned city by Le Corbusier, of the Rock Garden, Sukhna Lake, and grid-sector modernism.', 'Spring (Feb-Apr)', 'March', '["Rock Garden", "Sukhna Lake", "Rose Garden", "Capitol Complex", "Sector 17 Plaza"]', '#4f46e5'),
('Dadra and Nagar Haveli and Daman and Diu', 'dnh-and-dd', 'Portuguese Heritage Coast', 'A union territory of Daman''s Portuguese forts and beaches plus the green tribal belt of Dadra and Nagar Haveli.', 'Winter (Nov-Mar)', 'December', '["Moti Daman Fort", "Jampore Beach", "Dudhni Lake", "Nani Daman Church", "Vasona Lion Safari"]', '#14b8a6'),
('Delhi', 'delhi', 'The Eternal Capital', 'India''s capital territory of Mughal grandeur at Red Fort and Humayun''s Tomb, India Gate, and Old Delhi''s bazaars.', 'Winter (Oct-Mar)', 'November', '["India Gate", "Red Fort", "Qutub Minar", "Humayun''s Tomb", "Chandni Chowk"]', '#dc2626'),
('Jammu and Kashmir', 'jammu-and-kashmir', 'Paradise on Earth', 'A northern UT of Dal Lake houseboats, Vaishno Devi pilgrimage, Pahalgam valleys, and saffron fields.', 'Summer (Apr-Oct)', 'June', '["Dal Lake", "Vaishno Devi", "Pahalgam Valley", "Gulmarg Skiing", "Shalimar Bagh"]', '#1e40af'),
('Ladakh', 'ladakh', 'Land of High Passes', 'A trans-Himalayan desert of Pangong Lake, ancient monasteries, Khardung La, and stark moon-like landscapes.', 'Summer (May-Sep)', 'July', '["Pangong Lake", "Thiksey Monastery", "Khardung La", "Nubra Sand Dunes", "Shanti Stupa"]', '#0369a1'),
('Lakshadweep', 'lakshadweep', 'Coral Paradise', 'An Arabian Sea archipelago of coral atolls, lagoons, and untouched beaches off the Kerala coast.', 'Winter (Oct-Mar)', 'December', '["Agatti Beach", "Minicoy Island", "Scuba Lagoons", "Kalpeni Atoll", "Bangaram Island"]', '#0284c7'),
('Puducherry', 'puducherry', 'French Riviera of the East', 'A former French colony of mustard-yellow streets, Rock Beach promenade, Aurobindo Ashram, and Auroville.', 'Winter (Nov-Feb)', 'December', '["Rock Beach", "French Quarter", "Auroville", "Aurobindo Ashram", "Paradise Beach"]', '#f59e0b');

-- ============ DISTRICTS ============
INSERT INTO districts (state_id, name, description) VALUES
((SELECT id FROM states WHERE name='Andhra Pradesh'), 'Visakhapatnam', 'Port city district of beaches, hills, and the Eastern Ghats meeting the Bay of Bengal.'),
((SELECT id FROM states WHERE name='Andhra Pradesh'), 'Chittoor', 'Temple district home to Tirupati, one of the world''s most visited pilgrimage sites.'),
((SELECT id FROM states WHERE name='Andhra Pradesh'), 'Guntur', 'Coastal plains district of the ancient Amaravati Buddhist stupa and Kondaveedu fort.'),
((SELECT id FROM states WHERE name='Arunachal Pradesh'), 'Tawang', 'High Himalayan district of the 400-year-old Tawang Monastery and Sela Pass.'),
((SELECT id FROM states WHERE name='Arunachal Pradesh'), 'West Kameng', 'Alpine district of Dirang valley, hot springs, and apple orchards.'),
((SELECT id FROM states WHERE name='Arunachal Pradesh'), 'Papum Pare', 'Capital district around Itanagar with Ita Fort and tribal museums.'),
((SELECT id FROM states WHERE name='Assam'), 'Kamrup Metropolitan', 'Metro district of Guwahati with Kamakhya Temple and Brahmaputra riverfront.'),
((SELECT id FROM states WHERE name='Assam'), 'Golaghat', 'Gateway district to Kaziranga''s rhino grasslands and Numaligarh.'),
((SELECT id FROM states WHERE name='Assam'), 'Baksa', 'Foothill district sharing Manas National Park''s forests and golden langurs.'),
((SELECT id FROM states WHERE name='Bihar'), 'Patna', 'Capital district on the Ganga with Golghar granary and ancient Pataliputra sites.'),
((SELECT id FROM states WHERE name='Bihar'), 'Gaya', 'Pilgrimage district of Bodh Gaya''s Mahabodhi Temple and Vishnupad shrine.'),
((SELECT id FROM states WHERE name='Bihar'), 'Nalanda', 'Historic district of the ancient Nalanda university ruins and Rajgir hills.'),
((SELECT id FROM states WHERE name='Chhattisgarh'), 'Raipur', 'Capital district with museums, lakes, and access to Barnawapara wildlife.'),
((SELECT id FROM states WHERE name='Chhattisgarh'), 'Bastar', 'Tribal heartland district of Chitrakote Falls and Danteshwari Temple.'),
((SELECT id FROM states WHERE name='Chhattisgarh'), 'Bilaspur', 'Cultural district of Ratanpur temples and Achanakmar forests.'),
((SELECT id FROM states WHERE name='Gujarat'), 'Ahmedabad', 'Heritage city district of Sabarmati Ashram and UNESCO-listed old city pols.'),
((SELECT id FROM states WHERE name='Gujarat'), 'Gir Somnath', 'Coastal district of Somnath Jyotirlinga and Gir lion safaris.'),
((SELECT id FROM states WHERE name='Gujarat'), 'Kutch', 'Vast desert district of the white Rann, Mandvi beach, and handicraft villages.'),
((SELECT id FROM states WHERE name='Haryana'), 'Gurugram', 'Millennium city district of Kingdom of Dreams and Cyber Hub leisure.'),
((SELECT id FROM states WHERE name='Haryana'), 'Kurukshetra', 'Sacred district of the Mahabharata battlefield and Brahma Sarovar.'),
((SELECT id FROM states WHERE name='Haryana'), 'Faridabad', 'Industrial district of Surajkund crafts fair and Badkhal Lake.'),
((SELECT id FROM states WHERE name='Jharkhand'), 'Ranchi', 'Capital district of Hundru and Dassam waterfalls on the Chota Nagpur plateau.'),
((SELECT id FROM states WHERE name='Jharkhand'), 'Deoghar', 'Pilgrimage district of the Baidyanath Jyotirlinga temple town.'),
((SELECT id FROM states WHERE name='Jharkhand'), 'Dhanbad', 'Coal capital district of Maithon Dam and Topchanchi Lake.'),
((SELECT id FROM states WHERE name='Karnataka'), 'Mysuru', 'Royal district of Mysuru Palace, Chamundi Hills, and Dasara festivities.'),
((SELECT id FROM states WHERE name='Karnataka'), 'Ballari', 'Historic district of Hampi''s Vijayanagara ruins on the Tungabhadra.'),
((SELECT id FROM states WHERE name='Karnataka'), 'Bengaluru Urban', 'Tech capital district of Lalbagh gardens and Bangalore Palace.'),
((SELECT id FROM states WHERE name='Madhya Pradesh'), 'Bhopal', 'Lake city capital district of Upper Lake and Taj-ul-Masajid.'),
((SELECT id FROM states WHERE name='Madhya Pradesh'), 'Chhatarpur', 'Heritage district of Khajuraho''s Chandela temples and Panna tigers nearby.'),
((SELECT id FROM states WHERE name='Madhya Pradesh'), 'Ujjain', 'Ancient temple city district of Mahakaleshwar Jyotirlinga on the Shipra.'),
((SELECT id FROM states WHERE name='Maharashtra'), 'Mumbai', 'Financial capital district of the Gateway, Elephanta Caves, and Marine Drive.'),
((SELECT id FROM states WHERE name='Maharashtra'), 'Pune', 'Cultural capital district of Shaniwar Wada and Aga Khan Palace.'),
((SELECT id FROM states WHERE name='Maharashtra'), 'Aurangabad', 'Heritage district of Ellora and Ajanta caves plus Bibi Ka Maqbara.'),
((SELECT id FROM states WHERE name='Manipur'), 'Imphal West', 'Capital district of Kangla Palace and the women-run Ima Keithel market.'),
((SELECT id FROM states WHERE name='Manipur'), 'Bishnupur', 'Lakeside district of Loktak Lake and Keibul Lamjao floating park.'),
((SELECT id FROM states WHERE name='Meghalaya'), 'East Khasi Hills', 'Hill district of Shillong, Cherrapunji falls, and living root bridges.'),
((SELECT id FROM states WHERE name='Meghalaya'), 'West Jaintia Hills', 'Waterfall district of Krang Suri and Nartiang monoliths.'),
((SELECT id FROM states WHERE name='Mizoram'), 'Aizawl', 'Capital hill district of Durtlang viewpoints and the state museum.'),
((SELECT id FROM states WHERE name='Mizoram'), 'Champhai', 'Border district of Murlen forests and Champhai valley vineyards.'),
((SELECT id FROM states WHERE name='Nagaland'), 'Kohima', 'Capital hill district of the War Cemetery and Kisama Heritage Village.'),
((SELECT id FROM states WHERE name='Nagaland'), 'Dimapur', 'Gateway district of Kachari ruins and Diezephe craft village.'),
((SELECT id FROM states WHERE name='Odisha'), 'Puri', 'Holy coastal district of Jagannath Temple, Konark, and Puri Beach.'),
((SELECT id FROM states WHERE name='Odisha'), 'Khordha', 'Temple district around Bhubaneswar with Dhauli and Nandankanan.'),
((SELECT id FROM states WHERE name='Odisha'), 'Cuttack', 'Millennium city district of Barabati Fort and silver filigree work.'),
((SELECT id FROM states WHERE name='Punjab'), 'Amritsar', 'Holy city district of the Golden Temple and Wagah border ceremony.'),
((SELECT id FROM states WHERE name='Punjab'), 'Patiala', 'Royal district of Qila Mubarak and Sheesh Mahal museums.'),
((SELECT id FROM states WHERE name='Sikkim'), 'East Sikkim', 'Capital district of Gangtok''s MG Marg and Rumtek Monastery.'),
((SELECT id FROM states WHERE name='Sikkim'), 'North Sikkim', 'Alpine district of Yumthang Valley and Gurudongmar Lake.'),
((SELECT id FROM states WHERE name='Telangana'), 'Hyderabad', 'Pearl city district of Charminar, Golconda, and Hussain Sagar.'),
((SELECT id FROM states WHERE name='Telangana'), 'Warangal Urban', 'Kakatiya heritage district of Warangal Fort and Thousand Pillar Temple.'),
((SELECT id FROM states WHERE name='Tripura'), 'West Tripura', 'Capital district of Agartala''s Ujjayanta Palace and temples.'),
((SELECT id FROM states WHERE name='Tripura'), 'Gomati', 'Riverine district of Tripura Sundari Temple and Dumboor Lake.'),
((SELECT id FROM states WHERE name='Uttar Pradesh'), 'Agra', 'Mughal district of the Taj Mahal, Agra Fort, and Fatehpur Sikri.'),
((SELECT id FROM states WHERE name='Uttar Pradesh'), 'Varanasi', 'Eternal holy city district of Kashi Vishwanath and the Ganga ghats.'),
((SELECT id FROM states WHERE name='Uttar Pradesh'), 'Lucknow', 'Nawabi capital district of Bara Imambara and Rumi Darwaza.'),
((SELECT id FROM states WHERE name='Uttarakhand'), 'Dehradun', 'Valley capital district of Robber''s Cave and Mindrolling Monastery.'),
((SELECT id FROM states WHERE name='Uttarakhand'), 'Nainital', 'Lake district of Naini Lake and Naina Devi Temple.'),
((SELECT id FROM states WHERE name='Uttarakhand'), 'Rudraprayag', 'Pilgrim district of the Kedarnath Temple in the high Himalaya.'),
((SELECT id FROM states WHERE name='West Bengal'), 'Kolkata', 'Colonial capital district of Victoria Memorial and Howrah Bridge.'),
((SELECT id FROM states WHERE name='West Bengal'), 'Darjeeling', 'Hill district of the Himalayan toy train, Tiger Hill, and tea gardens.'),
((SELECT id FROM states WHERE name='Andaman and Nicobar Islands'), 'South Andaman', 'Island district of Port Blair''s Cellular Jail and Havelock beaches.'),
((SELECT id FROM states WHERE name='Chandigarh'), 'Chandigarh', 'Planned city district of the Rock Garden and Sukhna Lake.'),
((SELECT id FROM states WHERE name='Dadra and Nagar Haveli and Daman and Diu'), 'Daman', 'Coastal district of Moti Daman Fort and Jampore Beach.'),
((SELECT id FROM states WHERE name='Dadra and Nagar Haveli and Daman and Diu'), 'Dadra and Nagar Haveli', 'Green tribal district of Dudhni Lake and Vasona safari.'),
((SELECT id FROM states WHERE name='Delhi'), 'Delhi', 'Capital territory district of India Gate, Red Fort, and Qutub Minar.'),
((SELECT id FROM states WHERE name='Jammu and Kashmir'), 'Srinagar', 'Summer capital district of Dal Lake and Mughal gardens.'),
((SELECT id FROM states WHERE name='Jammu and Kashmir'), 'Jammu', 'Winter capital district and base for Vaishno Devi pilgrimage.'),
((SELECT id FROM states WHERE name='Jammu and Kashmir'), 'Anantnag', 'Valley district of Pahalgam meadows and Lidder river.'),
((SELECT id FROM states WHERE name='Ladakh'), 'Leh', 'High desert district of Pangong Lake, monasteries, and Shanti Stupa.'),
((SELECT id FROM states WHERE name='Ladakh'), 'Kargil', 'Western district of the Drass War Memorial and Suru Valley.'),
((SELECT id FROM states WHERE name='Lakshadweep'), 'Lakshadweep', 'Coral atoll district of Agatti and Minicoy lagoons.'),
((SELECT id FROM states WHERE name='Puducherry'), 'Puducherry', 'French Quarter district of Rock Beach and Aurobindo Ashram.');

-- ============ TOURIST SPOTS ============
INSERT INTO tourist_spots (district_id, name, description, category, latitude, longitude, rating, entry_fee, visit_duration) VALUES
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Visakhapatnam' AND s.name='Andhra Pradesh'), 'RK Beach Vizag', 'A lively city beach along Beach Road, popular for sunrise walks and submarine museum visits nearby.', 'Beach', 17.714500, 83.315700, 4.3, 'Free', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Visakhapatnam' AND s.name='Andhra Pradesh'), 'Kailasagiri Hill', 'A hilltop park with panoramic bay views, ropeway rides, and giant Shiva-Parvati statues.', 'Viewpoint', 17.749200, 83.341500, 4.4, 'Rs. 50', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Chittoor' AND s.name='Andhra Pradesh'), 'Tirumala Balaji Temple', 'One of the world''s richest and most visited temples, dedicated to Lord Venkateswara atop Tirumala hills.', 'Temple', 13.683100, 79.347200, 4.9, 'Free', '4-6 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Guntur' AND s.name='Andhra Pradesh'), 'Amaravati Stupa', 'Ancient 2nd-century Buddhist mahachaitya with carved limestone panels and a modern museum.', 'Heritage', 16.574600, 80.357000, 4.3, 'Free', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Tawang' AND s.name='Arunachal Pradesh'), 'Tawang Monastery', 'India''s largest monastery, a 400-year-old Gelugpa citadel overlooking the Tawang valley.', 'Monastery', 27.586700, 91.857200, 4.8, 'Free', '3-4 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Tawang' AND s.name='Arunachal Pradesh'), 'Sela Pass', 'A high-altitude pass at 13,700 ft with the sacred Sela Lake, often snow-covered.', 'Nature', 27.509000, 92.101700, 4.6, 'Free', '1-2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='West Kameng' AND s.name='Arunachal Pradesh'), 'Dirang Valley', 'A serene alpine valley of apple orchards, hot springs, and the Dirang Dzong fortress.', 'Valley', 27.360000, 92.240000, 4.5, 'Free', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Papum Pare' AND s.name='Arunachal Pradesh'), 'Ita Fort', 'A 14th-century brick fort in Itanagar built by the Jitari kings, among the oldest in the region.', 'Heritage', 27.100000, 93.616700, 4.0, 'Free', '1-2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Kamrup Metropolitan' AND s.name='Assam'), 'Kamakhya Temple', 'A revered Shakti shrine atop Nilachal Hill, center of the Ambubachi festival.', 'Temple', 26.166400, 91.705600, 4.7, 'Free', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Kamrup Metropolitan' AND s.name='Assam'), 'Umananda Island', 'The world''s smallest inhabited river island, with a Shiva temple mid-Brahmaputra.', 'Spiritual', 26.191700, 91.745800, 4.3, 'Free', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Golaghat' AND s.name='Assam'), 'Kaziranga Central Range', 'UNESCO grasslands sheltering two-thirds of the world''s one-horned rhinos, best by jeep safari.', 'Wildlife', 26.577500, 93.171100, 4.8, 'Rs. 100', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Baksa' AND s.name='Assam'), 'Manas National Park', 'A UNESCO tiger and elephant reserve in Himalayan foothills, home to golden langurs.', 'Wildlife', 26.725000, 90.950000, 4.6, 'Rs. 200', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Patna' AND s.name='Bihar'), 'Golghar', 'A 1786 beehive-shaped granary with panoramic Ganga views from its spiral stairway top.', 'Heritage', 25.620000, 85.140000, 4.0, 'Free', '1 hour'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Patna' AND s.name='Bihar'), 'Patna Museum', 'A colonial museum of Mauryan Didarganj Yakshi, fossils, and Mughal paintings.', 'Museum', 25.620900, 85.143800, 4.2, 'Rs. 15', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Gaya' AND s.name='Bihar'), 'Mahabodhi Temple', 'The UNESCO temple marking Buddha''s enlightenment, with the sacred Bodhi Tree.', 'Temple', 24.696000, 84.993000, 4.9, 'Free', '3-4 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Nalanda' AND s.name='Bihar'), 'Nalanda Ruins', 'Excavated remains of the ancient world''s greatest residential university (5th-12th century).', 'Heritage', 25.136700, 85.443700, 4.6, 'Rs. 40', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Raipur' AND s.name='Chhattisgarh'), 'Mahant Ghasidas Museum', 'A heritage museum of tribal art, inscriptions, and natural history in Raipur.', 'Museum', 21.237900, 81.639000, 4.1, 'Rs. 10', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Bastar' AND s.name='Chhattisgarh'), 'Chitrakote Falls', 'India''s widest waterfall on the Indravati, called the Niagara of India.', 'Waterfall', 19.207200, 81.699600, 4.7, 'Free', '3-4 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Bilaspur' AND s.name='Chhattisgarh'), 'Ratanpur Mahamaya Temple', 'An 11th-century Kalachuri temple complex, a major Shakti pilgrimage center.', 'Temple', 22.296800, 82.165000, 4.3, 'Free', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Ahmedabad' AND s.name='Gujarat'), 'Sabarmati Ashram', 'Gandhi''s 1917 ashram on the Sabarmati, origin of the Dandi March.', 'Heritage', 23.060700, 72.580600, 4.6, 'Free', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Ahmedabad' AND s.name='Gujarat'), 'Adalaj Stepwell', 'A five-storey 1498 stepwell of carved Indo-Islamic pillars and motifs.', 'Heritage', 23.167200, 72.582000, 4.5, 'Rs. 20', '1-2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Gir Somnath' AND s.name='Gujarat'), 'Somnath Temple', 'The first of the twelve Jyotirlingas, rebuilt Chalukya-style by the Arabian Sea.', 'Temple', 20.888000, 70.401300, 4.8, 'Free', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Gir Somnath' AND s.name='Gujarat'), 'Gir Lion Safari', 'The only wild home of Asiatic lions, explored via Sasan Gir gypsy safaris.', 'Wildlife', 21.124200, 70.661000, 4.7, 'Rs. 800', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Kutch' AND s.name='Gujarat'), 'White Rann of Kutch', 'An endless salt desert that glows under full-moon Rann Utsav nights from Dhordo.', 'Nature', 23.842000, 69.692000, 4.7, 'Rs. 100', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Kutch' AND s.name='Gujarat'), 'Mandvi Beach', 'A clean family beach with the Vijay Vilas Palace and shipbuilding yards nearby.', 'Beach', 22.816700, 69.350000, 4.2, 'Free', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Gurugram' AND s.name='Haryana'), 'Kingdom of Dreams', 'A Bollywood-style live entertainment and culture destination with Nautanki Mahal shows.', 'Entertainment', 28.455000, 77.090000, 4.3, 'Rs. 600', '4-5 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Kurukshetra' AND s.name='Haryana'), 'Brahma Sarovar', 'A vast sacred tank linked to the Mahabharata, lit by evening aarti and Deepotsav diyas.', 'Spiritual', 29.964000, 76.830000, 4.5, 'Free', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Faridabad' AND s.name='Haryana'), 'Surajkund Lake', 'A 10th-century reservoir hosting the famous February international crafts fair.', 'Lake', 28.284000, 77.283000, 4.3, 'Free', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Ranchi' AND s.name='Jharkhand'), 'Hundru Falls', 'A 98-metre plunge of the Subarnarekha river through forested plateau cliffs.', 'Waterfall', 23.450000, 85.650000, 4.4, 'Free', '3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Deoghar' AND s.name='Jharkhand'), 'Baidyanath Temple', 'One of the twelve Jyotirlingas, drawing lakhs of Kanwariya pilgrims each Shravan.', 'Temple', 24.492000, 86.697000, 4.8, 'Free', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Dhanbad' AND s.name='Jharkhand'), 'Maithon Dam', 'A serene reservoir on the Barakar with boating and a migratory-bird island.', 'Nature', 23.780000, 86.810000, 4.2, 'Free', '3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Mysuru' AND s.name='Karnataka'), 'Mysuru Palace', 'The illuminated Wodeyar royal palace, among India''s most visited monuments.', 'Palace', 12.305200, 76.655200, 4.8, 'Rs. 100', '3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Mysuru' AND s.name='Karnataka'), 'Chamundi Hills', 'A hilltop Shakti temple with city views and the Nandi statue climb.', 'Temple', 12.272000, 76.670000, 4.6, 'Free', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Ballari' AND s.name='Karnataka'), 'Virupaksha Temple Hampi', 'A living 7th-century temple amid Hampi''s boulder-strewn UNESCO ruinscape.', 'Heritage', 15.335000, 76.460000, 4.9, 'Free', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Ballari' AND s.name='Karnataka'), 'Vittala Temple', 'A Vijayanagara masterpiece with musical pillars and the iconic stone chariot.', 'Heritage', 15.334500, 76.470000, 4.8, 'Rs. 40', '3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Bengaluru Urban' AND s.name='Karnataka'), 'Lalbagh Botanical Garden', 'A 240-acre 1760 garden with a glass house flower show and ancient rock formations.', 'Garden', 12.950700, 77.584800, 4.5, 'Rs. 30', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Bhopal' AND s.name='Madhya Pradesh'), 'Upper Lake Bhopal', 'A vast 11th-century lake for boating and sunset views near Van Vihar.', 'Lake', 23.250000, 77.340000, 4.4, 'Free', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Bhopal' AND s.name='Madhya Pradesh'), 'Taj-ul-Masajid', 'One of Asia''s largest mosques, with a grand courtyard and minarets.', 'Heritage', 23.263000, 77.334000, 4.4, 'Free', '1-2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Chhatarpur' AND s.name='Madhya Pradesh'), 'Khajuraho Western Group', 'UNESCO Chandela temples famed for intricate nagara architecture and sculpture.', 'Heritage', 24.854000, 79.920000, 4.9, 'Rs. 40', '4-5 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Ujjain' AND s.name='Madhya Pradesh'), 'Mahakaleshwar Temple', 'A Jyotirlinga shrine famed for its pre-dawn Bhasma Aarti on the Shipra.', 'Temple', 23.182800, 75.777200, 4.9, 'Free', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Mumbai' AND s.name='Maharashtra'), 'Gateway of India', 'The iconic 1924 basalt arch by the harbour, gateway to Elephanta ferries.', 'Monument', 18.922000, 72.834700, 4.7, 'Free', '1-2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Mumbai' AND s.name='Maharashtra'), 'Elephanta Caves', 'UNESCO rock-cut Shaivite caves with the Trimurti sculpture, by harbour ferry.', 'Heritage', 18.963300, 72.931500, 4.5, 'Rs. 40', 'Half day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Pune' AND s.name='Maharashtra'), 'Shaniwar Wada', 'The 1732 Peshwa palace-fort with light-and-sound shows and massive gates.', 'Heritage', 18.519500, 73.855300, 4.4, 'Rs. 25', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Aurangabad' AND s.name='Maharashtra'), 'Ellora Caves', 'UNESCO monolithic Kailasa temple plus 33 Buddhist, Hindu, and Jain caves.', 'Heritage', 20.025000, 75.178000, 4.9, 'Rs. 40', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Aurangabad' AND s.name='Maharashtra'), 'Bibi Ka Maqbara', 'Aurangzeb''s son''s Taj-like mausoleum for his mother, the Deccan Taj.', 'Monument', 19.901500, 75.320000, 4.4, 'Rs. 25', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Imphal West' AND s.name='Manipur'), 'Kangla Palace', 'The ancient seat of Manipur kings with excavated ruins and sacred groves.', 'Heritage', 24.807000, 93.940000, 4.4, 'Rs. 10', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Imphal West' AND s.name='Manipur'), 'Ima Keithel Market', 'The world''s largest all-women market for textiles, produce, and crafts.', 'Market', 24.809000, 93.936000, 4.5, 'Free', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Bishnupur' AND s.name='Manipur'), 'Loktak Lake', 'The largest freshwater lake in the Northeast, dotted with floating phumdis.', 'Lake', 24.550000, 93.780000, 4.6, 'Free', 'Half day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Bishnupur' AND s.name='Manipur'), 'Keibul Lamjao Park', 'The world''s only floating national park, home to the Sangai deer.', 'Wildlife', 24.480000, 93.820000, 4.5, 'Rs. 50', '3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='East Khasi Hills' AND s.name='Meghalaya'), 'Nohkalikai Falls', 'India''s tallest plunge waterfall at 340m near Cherrapunji.', 'Waterfall', 25.275000, 91.686000, 4.7, 'Rs. 50', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='East Khasi Hills' AND s.name='Meghalaya'), 'Double Decker Root Bridge', 'The famed living root bridge of Nongriat, reached by 3,500 steps.', 'Nature', 25.244700, 91.670300, 4.8, 'Rs. 50', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='West Jaintia Hills' AND s.name='Meghalaya'), 'Krang Suri Falls', 'A turquoise plunge pool waterfall, among Meghalaya''s most photogenic.', 'Waterfall', 25.346800, 92.102600, 4.6, 'Rs. 50', '3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Aizawl' AND s.name='Mizoram'), 'Durtlang Hills', 'A panoramic viewpoint over Aizawl city, best at sunrise and night lights.', 'Viewpoint', 23.780000, 92.730000, 4.4, 'Free', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Aizawl' AND s.name='Mizoram'), 'Mizoram State Museum', 'A hilltop museum of Mizo tribal history, tools, and textiles.', 'Museum', 23.727000, 92.717000, 4.1, 'Rs. 20', '1-2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Champhai' AND s.name='Mizoram'), 'Murlen National Park', 'A dense evergreen forest park rich in birds and rare fauna near the Myanmar border.', 'Wildlife', 23.630000, 93.290000, 4.3, 'Rs. 50', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Kohima' AND s.name='Nagaland'), 'Kohima War Cemetery', 'A beautifully kept WWII memorial to Allied soldiers on Garrison Hill.', 'Memorial', 25.667000, 94.120000, 4.7, 'Free', '1-2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Kohima' AND s.name='Nagaland'), 'Kisama Heritage Village', 'The Naga heritage complex hosting the annual Hornbill Festival.', 'Heritage', 25.640000, 94.080000, 4.5, 'Rs. 30', '3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Dimapur' AND s.name='Nagaland'), 'Kachari Ruins', 'Megalithic mushroom-domed pillars of the 10th-century Kachari kingdom.', 'Heritage', 25.900000, 93.730000, 4.2, 'Free', '1-2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Puri' AND s.name='Odisha'), 'Jagannath Temple Puri', 'One of the Char Dham shrines, famed for Rath Yatra and Mahaprasad.', 'Temple', 19.804600, 85.818300, 4.9, 'Free', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Puri' AND s.name='Odisha'), 'Konark Sun Temple', 'The 13th-century chariot-shaped UNESCO temple to Surya by the sea.', 'Heritage', 19.887600, 86.094500, 4.9, 'Rs. 40', '3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Puri' AND s.name='Odisha'), 'Puri Beach', 'A golden beach of sand artists, surf schools, and evening crowds.', 'Beach', 19.798000, 85.824000, 4.4, 'Free', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Khordha' AND s.name='Odisha'), 'Dhauli Shanti Stupa', 'Ashoka''s peace pagoda on the Kalinga battlefield banks of the Daya.', 'Monument', 20.192000, 85.843000, 4.5, 'Free', '1-2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Cuttack' AND s.name='Odisha'), 'Barabati Fort', 'A 14th-century moated fort of the Ganga dynasty in the millennium city.', 'Heritage', 20.481000, 85.868000, 4.1, 'Free', '1-2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Amritsar' AND s.name='Punjab'), 'Golden Temple', 'Sikhism''s holiest shrine, a gold-plated sanctum in the Amrit Sarovar.', 'Temple', 31.620000, 74.876500, 5.0, 'Free', '3-4 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Amritsar' AND s.name='Punjab'), 'Jallianwala Bagh', 'The 1919 massacre memorial with the Martyrs'' Well and light show.', 'Memorial', 31.619000, 74.880000, 4.7, 'Free', '1-2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Amritsar' AND s.name='Punjab'), 'Wagah Border Ceremony', 'The electrifying sunset retreat ceremony at the Attari-Wagah border.', 'Experience', 31.604500, 74.573500, 4.8, 'Free', '3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Patiala' AND s.name='Punjab'), 'Qila Mubarak', 'A 1764 royal fort complex of palaces, including the Ran Baas guesthouse.', 'Heritage', 30.324000, 76.402000, 4.3, 'Rs. 20', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='East Sikkim' AND s.name='Sikkim'), 'MG Marg Gangtok', 'A litter-free promenade of cafes and shops in the heart of Gangtok.', 'Leisure', 27.331000, 88.613000, 4.6, 'Free', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='East Sikkim' AND s.name='Sikkim'), 'Rumtek Monastery', 'Sikkim''s largest monastery, seat of the Karmapa with a golden stupa.', 'Monastery', 27.289000, 88.561000, 4.7, 'Free', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='North Sikkim' AND s.name='Sikkim'), 'Yumthang Valley', 'The valley of flowers with rhododendron slopes and hot springs.', 'Valley', 27.830000, 88.700000, 4.8, 'Free', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='North Sikkim' AND s.name='Sikkim'), 'Gurudongmar Lake', 'A sacred 17,800-ft lake among the world''s highest, blazing blue.', 'Lake', 28.020000, 88.710000, 4.9, 'Free', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Hyderabad' AND s.name='Telangana'), 'Charminar', 'Hyderabad''s 1591 four-minaret icon amid Laad Bazaar bangles.', 'Monument', 17.361600, 78.474700, 4.7, 'Rs. 25', '1-2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Hyderabad' AND s.name='Telangana'), 'Golconda Fort', 'A hilltop Qutb Shahi fortress famed for Kohinoor lore and sound shows.', 'Heritage', 17.383300, 78.401100, 4.6, 'Rs. 25', '3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Warangal Urban' AND s.name='Telangana'), 'Thousand Pillar Temple', 'A Kakatiya star-shaped temple of carved pillars and Nandi pavilions.', 'Temple', 18.003400, 79.576800, 4.6, 'Free', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='West Tripura' AND s.name='Tripura'), 'Ujjayanta Palace', 'Agartala''s white palace turned museum of Tripura''s royal heritage.', 'Palace', 23.837000, 91.282000, 4.5, 'Rs. 20', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Gomati' AND s.name='Tripura'), 'Tripura Sundari Temple', 'A Shakti shrine at Udaipur famed for peda prasad and Diwali fair.', 'Temple', 23.533000, 91.480000, 4.6, 'Free', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Agra' AND s.name='Uttar Pradesh'), 'Taj Mahal', 'The ivory marble wonder of the world, Shah Jahan''s ode to Mumtaz.', 'Monument', 27.175100, 78.042100, 5.0, 'Rs. 250', '3-4 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Agra' AND s.name='Uttar Pradesh'), 'Agra Fort', 'Akbar''s red sandstone fortress-palace with Taj views from Musamman Burj.', 'Heritage', 27.179500, 78.021100, 4.7, 'Rs. 50', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Varanasi' AND s.name='Uttar Pradesh'), 'Kashi Vishwanath Corridor', 'The grand corridor to a Jyotirlinga shrine beside the Ganga.', 'Temple', 25.310900, 83.010700, 4.9, 'Free', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Varanasi' AND s.name='Uttar Pradesh'), 'Dashashwamedh Ghat', 'The main ghat famed for its fire-lit Ganga Aarti every evening.', 'Spiritual', 25.308000, 83.009000, 4.8, 'Free', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Lucknow' AND s.name='Uttar Pradesh'), 'Bara Imambara', 'Asaf-ud-Daula''s 1784 hall with the Bhool Bhulaiya maze and Shahi Baoli.', 'Heritage', 26.869000, 80.913000, 4.6, 'Rs. 50', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Dehradun' AND s.name='Uttarakhand'), 'Robber''s Cave', 'A river cave gorge at Gucchu Pani for wading between limestone walls.', 'Nature', 30.375000, 78.060000, 4.4, 'Rs. 30', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Dehradun' AND s.name='Uttarakhand'), 'Mindrolling Monastery', 'A Tibetan Buddhist monastery with a 60m stupa and muralled halls.', 'Monastery', 30.269000, 78.007000, 4.6, 'Free', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Nainital' AND s.name='Uttarakhand'), 'Naini Lake', 'The kidney-shaped lake at the heart of Nainital for boating and Mall Road strolls.', 'Lake', 29.382000, 79.454000, 4.6, 'Free', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Rudraprayag' AND s.name='Uttarakhand'), 'Kedarnath Temple', 'A Jyotirlinga shrine near Mandakini headwaters, rebuilt after 2013.', 'Temple', 30.734000, 79.067000, 4.9, 'Free', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Kolkata' AND s.name='West Bengal'), 'Victoria Memorial', 'The white marble museum of colonial history set in 64 acres of gardens.', 'Museum', 22.544800, 88.342600, 4.7, 'Rs. 30', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Kolkata' AND s.name='West Bengal'), 'Howrah Bridge', 'The 1943 cantilever icon over the Hooghly, among the world''s busiest bridges.', 'Bridge', 22.585000, 88.346000, 4.6, 'Free', '1 hour'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Kolkata' AND s.name='West Bengal'), 'Dakshineswar Temple', 'Ramakrishna''s Kali temple on the Hooghly with twelve Shiva shrines.', 'Temple', 22.655000, 88.357000, 4.8, 'Free', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Darjeeling' AND s.name='West Bengal'), 'Tiger Hill Sunrise', 'The classic Kanchenjunga and Everest sunrise viewpoint above Darjeeling.', 'Viewpoint', 27.000000, 88.280000, 4.7, 'Rs. 50', 'Half day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Darjeeling' AND s.name='West Bengal'), 'Batasia Loop Railway', 'The spiral toy-train loop with a Gorkha memorial and mountain panorama.', 'Heritage', 27.020000, 88.250000, 4.5, 'Rs. 30', '1-2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='South Andaman' AND s.name='Andaman and Nicobar Islands'), 'Cellular Jail', 'The colonial prison-memorial of freedom fighters with an evening sound show.', 'Memorial', 11.675000, 92.749000, 4.8, 'Rs. 30', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='South Andaman' AND s.name='Andaman and Nicobar Islands'), 'Radhanagar Beach', 'A Blue-Flag beach on Havelock with powder sand and sunset points.', 'Beach', 11.976000, 92.953000, 4.9, 'Free', 'Half day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Chandigarh' AND s.name='Chandigarh'), 'Rock Garden', 'Nek Chand''s folk-art garden built from urban waste and boulders.', 'Garden', 30.752500, 76.810100, 4.6, 'Rs. 30', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Chandigarh' AND s.name='Chandigarh'), 'Sukhna Lake', 'A Shivalik-foothill reservoir for rowing, jogging, and sunsets.', 'Lake', 30.743000, 76.820000, 4.5, 'Free', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Daman' AND s.name='Dadra and Nagar Haveli and Daman and Diu'), 'Moti Daman Fort', 'A 16th-century Portuguese fort with lighthouse views over the sea.', 'Heritage', 20.417000, 72.832000, 4.1, 'Free', '1-2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Daman' AND s.name='Dadra and Nagar Haveli and Daman and Diu'), 'Jampore Beach', 'A calm black-sand beach for swimming and water sports near Nani Daman.', 'Beach', 20.400000, 72.830000, 4.2, 'Free', '2-3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Dadra and Nagar Haveli' AND s.name='Dadra and Nagar Haveli and Daman and Diu'), 'Dudhni Lake', 'A reservoir lake ringed by hills, popular for camping and water sports.', 'Lake', 20.280000, 73.050000, 4.2, 'Free', '3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Delhi' AND s.name='Delhi'), 'India Gate', 'The 42m war memorial arch on Kartavya Path, floodlit at night.', 'Monument', 28.612900, 77.229500, 4.8, 'Free', '1-2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Delhi' AND s.name='Delhi'), 'Qutub Minar', 'The 73m victory tower amid Indo-Islamic ruins, a UNESCO site.', 'Heritage', 28.524500, 77.185500, 4.7, 'Rs. 40', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Delhi' AND s.name='Delhi'), 'Red Fort', 'Shah Jahan''s 17th-century walled palace of the Mughal emperors.', 'Heritage', 28.656200, 77.241000, 4.6, 'Rs. 50', '3 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Delhi' AND s.name='Delhi'), 'Humayun''s Tomb', 'The garden-tomb prototype of the Taj, a UNESCO Mughal masterpiece.', 'Heritage', 28.593100, 77.250700, 4.7, 'Rs. 40', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Srinagar' AND s.name='Jammu and Kashmir'), 'Dal Lake', 'The Himalayan urban lake of houseboats, shikaras, and floating markets.', 'Lake', 34.100000, 74.870000, 4.8, 'Free', 'Half day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Srinagar' AND s.name='Jammu and Kashmir'), 'Shalimar Bagh', 'Jahangir''s terraced Mughal garden of fountains and chinar trees.', 'Garden', 34.149200, 74.873300, 4.5, 'Rs. 30', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Jammu' AND s.name='Jammu and Kashmir'), 'Vaishno Devi Shrine', 'The Trikuta cave shrine of Mata Vaishno Devi, among India''s busiest pilgrimages.', 'Temple', 33.030800, 74.949400, 4.9, 'Free', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Anantnag' AND s.name='Jammu and Kashmir'), 'Pahalgam Valley', 'A Lidder-valley meadow town, base for Amarnath and Betaab Valley trips.', 'Valley', 34.010000, 75.320000, 4.8, 'Free', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Leh' AND s.name='Ladakh'), 'Pangong Lake', 'The high-altitude blue lake shifting shades across the Changthang plateau.', 'Lake', 33.850000, 78.670000, 4.9, 'Rs. 20', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Leh' AND s.name='Ladakh'), 'Shanti Stupa', 'A white hilltop peace pagoda with Leh town and Stok range views.', 'Monument', 34.170000, 77.570000, 4.7, 'Free', '1-2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Leh' AND s.name='Ladakh'), 'Leh Palace', 'A 17th-century nine-storey royal palace overlooking old Leh town.', 'Heritage', 34.168000, 77.585000, 4.4, 'Rs. 30', '1-2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Kargil' AND s.name='Ladakh'), 'Kargil War Memorial Drass', 'The 1999 war memorial at Drass, second-coldest inhabited place on Earth.', 'Memorial', 34.430000, 75.750000, 4.8, 'Free', '2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Lakshadweep' AND s.name='Lakshadweep'), 'Agatti Island Beach', 'A coral-island beach with lagoon kayaking and diving off Agatti.', 'Beach', 10.850000, 72.190000, 4.7, 'Free', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Lakshadweep' AND s.name='Lakshadweep'), 'Minicoy Island', 'A crescent island of tuna culture, lighthouse, and coral reefs.', 'Island', 8.280000, 73.050000, 4.6, 'Free', 'Full day'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Puducherry' AND s.name='Puducherry'), 'Rock Beach Promenade', 'The Bay-side boulevard for sunrise walks past the Gandhi statue.', 'Waterfront', 11.936000, 79.835000, 4.6, 'Free', '1-2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Puducherry' AND s.name='Puducherry'), 'Sri Aurobindo Ashram', 'The spiritual community founded by Sri Aurobindo and the Mother.', 'Spiritual', 11.937000, 79.834000, 4.7, 'Free', '1-2 hours'),
((SELECT d.id FROM districts d JOIN states s ON d.state_id=s.id WHERE d.name='Puducherry' AND s.name='Puducherry'), 'Auroville Matrimandir', 'The golden meditation globe of the experimental universal township.', 'Spiritual', 11.992000, 79.812000, 4.7, 'Free', 'Half day');

-- ============ ACCOMMODATIONS ============
INSERT INTO accommodations (tourist_spot_id, name, type, tier, price_per_night, rating, amenities, address) VALUES
((SELECT id FROM tourist_spots WHERE name='Tirumala Balaji Temple'), 'Tirupati Temple View Hotel', 'Hotel', 'Deluxe', 3500, 4.3, '["WiFi", "Restaurant", "Parking", "Temple Shuttle"]', 'Tirupati Town Center'),
((SELECT id FROM tourist_spots WHERE name='Kaziranga Central Range'), 'Kaziranga Jungle Resort', 'Resort', 'Deluxe', 6000, 4.5, '["Safari Booking", "Pool", "Restaurant", "WiFi", "Bonfire"]', 'Kohora, Kaziranga'),
((SELECT id FROM tourist_spots WHERE name='Kaziranga Central Range'), 'Kohora Village Homestay', 'Homestay', 'Budget', 1800, 4.2, '["Breakfast", "WiFi", "Village Walk"]', 'Kohora Village'),
((SELECT id FROM tourist_spots WHERE name='Mahabodhi Temple'), 'Bodhi Luxury Retreat', 'Resort', 'Luxury', 8000, 4.6, '["Spa", "Meditation Hall", "Pool", "Restaurant", "WiFi"]', 'Bodh Gaya'),
((SELECT id FROM tourist_spots WHERE name='Mahabodhi Temple'), 'Bodh Gaya Pilgrim Stay', 'Hotel', 'Budget', 1500, 4.0, '["WiFi", "Restaurant", "Temple Shuttle"]', 'Near Mahabodhi Temple'),
((SELECT id FROM tourist_spots WHERE name='Somnath Temple'), 'Somnath Sea View Hotel', 'Hotel', 'Deluxe', 3000, 4.2, '["Sea View", "Restaurant", "WiFi", "Parking"]', 'Somnath Beach Road'),
((SELECT id FROM tourist_spots WHERE name='White Rann of Kutch'), 'Rann Utsav Tent City', 'Resort', 'Luxury', 9000, 4.5, '["Cultural Shows", "Camel Safari", "All Meals", "Bonfire"]', 'Dhordo, Kutch'),
((SELECT id FROM tourist_spots WHERE name='Mysuru Palace'), 'Mysuru Heritage Hotel', 'Hotel', 'Deluxe', 4000, 4.4, '["Heritage", "Pool", "Restaurant", "WiFi"]', 'Mysuru City Center'),
((SELECT id FROM tourist_spots WHERE name='Virupaksha Temple Hampi'), 'Hampi Riverside Homestay', 'Homestay', 'Budget', 1600, 4.3, '["Breakfast", "WiFi", "Cycle Rental", "River View"]', 'Virupapur Gadde, Hampi'),
((SELECT id FROM tourist_spots WHERE name='Khajuraho Western Group'), 'Khajuraho Temple Town Hotel', 'Hotel', 'Deluxe', 3200, 4.2, '["Pool", "Restaurant", "WiFi", "Guide Desk"]', 'Khajuraho'),
((SELECT id FROM tourist_spots WHERE name='Mahakaleshwar Temple'), 'Mahakal Residency Ujjain', 'Hotel', 'Budget', 1400, 4.0, '["WiFi", "Temple Shuttle", "Restaurant"]', 'Near Mahakaleshwar'),
((SELECT id FROM tourist_spots WHERE name='Gateway of India'), 'Mumbai Harbour Luxury Hotel', 'Hotel', 'Luxury', 12000, 4.6, '["Sea View", "Pool", "Spa", "Restaurant", "WiFi"]', 'Colaba, Mumbai'),
((SELECT id FROM tourist_spots WHERE name='Gateway of India'), 'Colaba Backpacker Hostel', 'Homestay', 'Budget', 900, 4.1, '["WiFi", "Lockers", "Cafe", "Walking Tours"]', 'Colaba, Mumbai'),
((SELECT id FROM tourist_spots WHERE name='Ellora Caves'), 'Ellora Heritage Stay', 'Hotel', 'Deluxe', 2800, 4.2, '["Restaurant", "WiFi", "Parking", "Guide Desk"]', 'Ellora Village'),
((SELECT id FROM tourist_spots WHERE name='Golden Temple'), 'Amritsar Golden Temple View', 'Hotel', 'Deluxe', 3500, 4.4, '["Temple View", "Restaurant", "WiFi", "Langar Info"]', 'Near Golden Temple'),
((SELECT id FROM tourist_spots WHERE name='Golden Temple'), 'Amritsar Old City Homestay', 'Homestay', 'Budget', 1300, 4.1, '["Breakfast", "WiFi", "Food Walk"]', 'Old City, Amritsar'),
((SELECT id FROM tourist_spots WHERE name='Taj Mahal'), 'Agra Taj View Luxury', 'Hotel', 'Luxury', 9500, 4.6, '["Taj View Rooftop", "Pool", "Spa", "Restaurant", "WiFi"]', 'Taj East Gate Road, Agra'),
((SELECT id FROM tourist_spots WHERE name='Taj Mahal'), 'Agra Budget Inn', 'Hotel', 'Budget', 1100, 3.9, '["WiFi", "Restaurant"]', 'Agra Cantt'),
((SELECT id FROM tourist_spots WHERE name='Dashashwamedh Ghat'), 'Varanasi Ghat Heritage Homestay', 'Homestay', 'Deluxe', 3800, 4.5, '["Ganga View", "Aarti Access", "Breakfast", "WiFi"]', 'Godowlia, Varanasi'),
((SELECT id FROM tourist_spots WHERE name='Dal Lake'), 'Dal Lake Deluxe Houseboat', 'Homestay', 'Deluxe', 5500, 4.5, '["Shikara Ride", "All Meals", "Heating", "WiFi"]', 'Dal Lake, Srinagar'),
((SELECT id FROM tourist_spots WHERE name='Pangong Lake'), 'Pangong Lakeside Camp', 'Resort', 'Deluxe', 4500, 4.3, '["Heated Tents", "All Meals", "Bonfire", "Oxygen Support"]', 'Spangmik, Pangong'),
((SELECT id FROM tourist_spots WHERE name='Kedarnath Temple'), 'Kedarnath Yatri Niwas', 'Hotel', 'Budget', 1000, 3.8, '["Dormitory", "Hot Water", "Bhojanalaya"]', 'Kedarnath Town'),
((SELECT id FROM tourist_spots WHERE name='Cellular Jail'), 'Port Blair Sea View Resort', 'Resort', 'Deluxe', 5000, 4.3, '["Sea View", "Pool", "Dive Desk", "Restaurant", "WiFi"]', 'Corbyn''s Cove Road, Port Blair'),
((SELECT id FROM tourist_spots WHERE name='India Gate'), 'Delhi Central Hotel', 'Hotel', 'Deluxe', 4500, 4.3, '["Metro Access", "Restaurant", "WiFi", "Parking"]', 'Connaught Place, Delhi'),
((SELECT id FROM tourist_spots WHERE name='Charminar'), 'Hyderabad Old City Hotel', 'Hotel', 'Budget', 1600, 4.0, '["WiFi", "Restaurant", "Bazaar Walk"]', 'Laad Bazaar, Hyderabad'),
((SELECT id FROM tourist_spots WHERE name='Victoria Memorial'), 'Kolkata Park Street Hotel', 'Hotel', 'Deluxe', 4200, 4.4, '["Heritage", "Restaurant", "WiFi", "Tram Tour Desk"]', 'Park Street, Kolkata'),
((SELECT id FROM tourist_spots WHERE name='MG Marg Gangtok'), 'Gangtok MG Marg Hotel', 'Hotel', 'Deluxe', 3600, 4.3, '["Mountain View", "Heating", "Restaurant", "WiFi"]', 'MG Marg, Gangtok'),
((SELECT id FROM tourist_spots WHERE name='Rock Beach Promenade'), 'Pondicherry French Quarter Villa', 'Hotel', 'Deluxe', 4800, 4.5, '["French Villa", "Courtyard", "Cycles", "WiFi", "Breakfast"]', 'White Town, Puducherry');


-- from 20260926000001_fix_map_data_mismatches.sql
UPDATE districts
SET name = 'Ajmer',
    description = 'Home to the sacred town of Pushkar with its holy lake and the famous camel fair, plus Ajmer Sharif Dargah.'
WHERE name = 'Pushkar'
  AND state_id = (SELECT id FROM states WHERE name = 'Rajasthan');
UPDATE districts
SET name = 'Kanyakumari'
WHERE name = 'Kanniyakumari'
  AND state_id = (SELECT id FROM states WHERE name = 'Tamil Nadu');
