"""Assemble preview/ : production dist + PHP api + local SQLite DB.

Regenerates everything from scratch so the preview always matches the repo:
  preview/            <- dist/* (static frontend, same-origin /api)
  preview/api/        <- api/*.php
  preview/config/config.php (sqlite, git-ignored via preview/)
  preview/trvlstory.db      (schema.sqlite.sql + seed.sql)

Usage: python3 scripts/make_preview.py
Serve: php -S localhost:8080 -t preview   (use scripts/preview.sh)
"""
import pathlib
import shutil
import sqlite3

ROOT = pathlib.Path(__file__).resolve().parent.parent
PREVIEW = ROOT / "preview"
DIST = ROOT / "dist"

shutil.rmtree(PREVIEW, ignore_errors=True)
(PREVIEW / "api").mkdir(parents=True)
(PREVIEW / "config").mkdir(parents=True)

for item in DIST.iterdir():
    dest = PREVIEW / item.name
    if item.is_dir():
        shutil.copytree(item, dest)
    else:
        shutil.copy2(item, dest)

for php in (ROOT / "api").glob("*.php"):
    shutil.copy2(php, PREVIEW / "api" / php.name)

db_path = PREVIEW / "trvlstory.db"
if db_path.exists():
    db_path.unlink()
con = sqlite3.connect(db_path)
con.executescript((ROOT / "database" / "schema.sqlite.sql").read_text(encoding="utf-8"))
con.executescript((ROOT / "database" / "seed.sql").read_text(encoding="utf-8"))
con.commit()
states = con.execute("select count(*) from states").fetchone()[0]
con.close()

(PREVIEW / "config" / "config.php").write_text(
    """<?php
// LOCAL PREVIEW ONLY (auto-generated by scripts/make_preview.py).
return ['db' => ['driver' => 'sqlite', 'path' => __DIR__ . '/../trvlstory.db']];
""",
    encoding="utf-8",
)
print(f"preview ready: {states} states, db={db_path.stat().st_size // 1024} KB")
