"""Convert Supabase (Postgres) seed migrations to portable SQL.

Reads the INSERT statements from supabase/migrations seed files plus the
fix-migration UPDATEs, and writes database/seed.sql which imports cleanly
into BOTH MySQL/MariaDB (production) and SQLite (local preview).

Conversions applied:
  - Postgres text[] literals '{"a","b"}' -> JSON '["a","b"]' ('' escaped)
  - '{}' -> '[]'
  - Trailing ON CONFLICT ... DO NOTHING stripped (import into an empty DB)
  - Fix-migration UPDATEs copied verbatim (plain UPDATE is portable)

Usage: python3 scripts/seed_convert.py
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MIG = ROOT / "supabase" / "migrations"
OUT = ROOT / "database" / "seed.sql"

SOURCES = [
    "20260924082941_seed_travel_data.sql",
    "20260925035138_seed_agent_marketplace_data.sql",
    "20260926000002_seed_remaining_states.sql",
    "20260926000001_fix_map_data_mismatches.sql",  # UPDATEs only
]


def parse_pg_array(inner):
    """Parse the inside of a Postgres {"..",".."} literal into a list."""
    items = []
    i, n = 0, len(inner)
    while i < n:
        while i < n and inner[i] in " \t\n\r,":
            i += 1
        if i >= n:
            break
        if inner[i] == '"':
            i += 1
            buf = []
            while i < n:
                ch = inner[i]
                if ch == "\\" and i + 1 < n:
                    buf.append(inner[i + 1])
                    i += 2
                elif ch == '"':
                    if i + 1 < n and inner[i + 1] == '"':
                        buf.append('"')
                        i += 2
                    else:
                        i += 1
                        break
                else:
                    buf.append(ch)
                    i += 1
            items.append("".join(buf))
        else:
            j = i
            while j < n and inner[j] != ",":
                j += 1
            items.append(inner[i:j].strip())
            i = j
    return items


def pg_array_to_json(literal):
    """'{"a","b"}' (SQL literal w/ '' escapes) -> '["a","b"]' SQL literal."""
    assert literal.startswith("'{") and literal.endswith("}'"), literal[:60]
    body = literal[1:-1]  # strip outer single quotes; '' stays for now
    if body == "{}":
        return "'[]'"
    items = parse_pg_array(body[1:-1])
    # restore apostrophes, then JSON-encode, then re-escape for SQL
    items = [it.replace("''", "'") for it in items]
    return "'" + json.dumps(items, ensure_ascii=False).replace("'", "''") + "'"


ARRAY_RE = re.compile(r"'\{(?:[^']|'')*?\}'")
CONFLICT_RE = re.compile(r"\s*ON\s+CONFLICT[^;]*?DO\s+NOTHING\s*;", re.IGNORECASE)
COMMENT_RE = re.compile(r"(--[^\n]*|/\*.*?\*/)", re.DOTALL)


def convert_inserts(text):
    # Only transform SQL code - leave comments verbatim (they may mention
    # "ON CONFLICT DO NOTHING").
    out = []
    for i, chunk in enumerate(COMMENT_RE.split(text)):
        if i % 2 == 1:  # comment segment
            out.append(chunk)
            continue

        def repl(m):
            lit = m.group(0)
            if lit == "'{}'":
                return "'[]'"
            return pg_array_to_json(lit)

        chunk = ARRAY_RE.sub(repl, chunk)
        chunk = CONFLICT_RE.sub(";", chunk)
        out.append(chunk)
    return "".join(out)


def main():
    parts = [
        "-- Travel Stories seed data (all 36 states/UTs + marketplace).",
        "-- GENERATED by scripts/seed_convert.py — do not edit by hand.",
        "-- Import ONCE into an empty DB: schema FIRST, then this file.",
        "",
    ]
    for name in SOURCES:
        src = MIG / name
        if not src.exists():
            print(f"missing source: {name}", file=sys.stderr)
            sys.exit(1)
        text = src.read_text(encoding="utf-8")
        if "UPDATE " in text and "INSERT " not in text:
            # fix migration: copy UPDATE statements verbatim
            updates = []
            inside = False
            for ln in text.splitlines():
                s = ln.strip()
                if s.upper().startswith("UPDATE"):
                    inside = True
                if inside:
                    if s == "" or s.startswith("--"):
                        continue
                    updates.append(ln)
                    if s.endswith(";"):
                        inside = False
            parts.append(f"-- from {name}")
            parts.extend(updates)
            parts.append("")
        else:
            parts.append(f"-- from {name}")
            parts.append(convert_inserts(text))
            parts.append("")
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
